(function(root){
  'use strict';
  const C=root.DanzigCivic,R=root.DanzigResidences,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),n=x=>Number(x||0).toLocaleString('ru-RU',{maximumFractionDigits:1});
  function person(s,p){const a=p.civic,g=C.group(s,p);return `<section class="mind-section"><div class="section-label">ОБЩЕСТВЕННАЯ ЖИЗНЬ</div><p>${g?'Участник «'+esc(g.name)+'». ':''}Нарушений: ${a.offences} · внимание стражи ${n(a.heat)} / 100.</p>${a.lastMotive?`<p class="muted">Последний мотив: ${esc(a.lastMotive)}.</p>`:''}${a.service||a.fineDue?`<p>Общественные работы: ${a.service} мин. · остаток штрафов: ${n(a.fineDue)} тал.</p>`:''}</section>`;}
  function homes(){return `<section class="residence-types"><span class="eyebrow">ЖИЛЬЁ ПО ПОЛОЖЕНИЮ СЕМЬИ</span><h3>Дома и поместья</h3><div class="ledger-kpis">${Object.entries(R.kinds).map(([id,r])=>`<article class="ledger-notice"><b>${esc(r.name)}</b><p>${n(r.cost)} тал. · от ${r.days} дней · ${r.capacity} мест</p><small>${id==='cottage'?'За стеной':id==='townhouse'?'Внутри городских стен':'Только дворянский квартал и семья с взрослым дворянином'} · аренда ×${r.rent}, сбор с двора ×${r.tax}, улучшения ×${r.upgrade}</small></article>`).join('')}</div><p class="muted">Это виды жилых зданий. Их уровни и дополнительные улучшения развиваются отдельно. Старые дома классифицированы по району без повторной оплаты.</p></section>`;}
  function render(s,card){const v=s.civic,t=v.totals,groups=v.groups.filter(g=>g.active),name=id=>esc(s.person(id)?.name||'—');
    return `<section class="civic-life"><span class="eyebrow">СВЯЗИ, КОНФЛИКТЫ И СТРАЖА</span><h3>Социальная жизнь города</h3><div class="ledger-kpis">${card('Личных встреч',t.meetings)}${card('Взаимопомощь',n(t.aid)+' тал.','Из кошельков жителей')}${card('Наставничество / примирения',t.mentoring+' / '+t.reconciled)}${card('Кражи / драки',t.thefts+' / '+t.brawls,'Включая замеченные попытки')}${card('Раскрыто дел',t.solved,'В работе: '+v.cases.filter(c=>c.status==='open'&&c.reported).length)}${card('Возмещено / штрафы',n(t.recovered)+' / '+n(t.fines)+' тал.')}</div><details><summary>Почему жители нарушают закон</summary><p>Нужда, корысть, личная вражда и поддержка сообщников конкурируют с обычными целями. Осторожность, сочувствие и внимание стражи влияют на выбор. Цель должна находиться рядом; уход участника отменяет действие. Кража переводит реальные деньги, драка ухудшает здоровье и отношения. Стража расследует сообщения, опираясь на свидетелей; раскрытие не гарантировано. Штрафы и возмещение зависят от кошелька нарушителя.</p></details><h3>Уличные компании · ${groups.length}</h3>${groups.map(g=>`<p class="ledger-notice"><b>${esc(g.name)}</b> · с дня ${g.formed+1}<br>${g.members.map(name).join(', ')}<br><small>Прикрывают друг друга при встречах; присутствующий сообщник получает четверть украденного. Без совместной активности компания распадается.</small></p>`).join('')||'<p class="muted">Банд пока нет. Они могут сложиться при личной встрече знакомых повторных нарушителей; готовые банды не создаются при запуске.</p>'}<h3>Дела стражи</h3><div class="ledger-table-wrap"><table><thead><tr><th>День / участники</th><th>Мотив</th><th>Происшествие</th><th>Состояние</th><th>Ущерб / возмещение</th></tr></thead><tbody>${v.cases.slice(0,30).map(c=>`<tr><td>${c.day+1} · ${name(c.actorId)}<br>Пострадавший: ${name(c.victimId)}</td><td>${esc(C.motives[c.motive])}</td><td>${C.labels[c.kind]}<br>${esc(s.building(c.buildingId)?.name)}<br>Свидетелей: ${c.witnesses.length}</td><td>${c.status==='solved'?'Раскрыто':c.status==='closed'?'Закрыто без раскрытия':c.reported?'Расследование':'Не заявлено'}</td><td>${n(c.amount)} / ${n(c.recovered)} тал.</td></tr>`).join('')||'<tr><td colspan="5">Правонарушений пока не было.</td></tr>'}</tbody></table></div><details class="civic-chronicle" open><summary>Последние социальные события</summary>${v.history.slice(0,15).map(h=>`<p class="ledger-notice"><small>День ${h.day+1} · ${esc(C.labels[h.kind])}</small><br>${esc(h.text)}</p>`).join('')||'<p class="muted">История появится после личных встреч жителей.</p>'}</details></section>`;
  }
  root.DanzigCivicView={person,homes,render};
})(window);
