(function(root){
  'use strict';
  const Finance=typeof module!=='undefined'&&module.exports?require('./finance.js'):root.DanzigFinance;
  const Agreements=typeof module!=='undefined'&&module.exports?require('./agreements.js'):root.DanzigAgreements;
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),round=n=>Math.round(n*100)/100;
  const demand={grain:65,flour:45,bread:80,fish:45,wood:45,tools:8,wool:20,cloth:10,clothes:5,planks:20,furniture:3,coal:25,iron:12,clay:25,pottery:5};
  function ensure(s,base){s.commerce??={sinceDay:s.day,levyEnabled:true,levyRate:15,autoExport:true,reserveDays:2,stock:Object.fromEntries(Object.keys(base).map(k=>[k,0])),prices:{...base},history:[],days:[],orders:[],lastDay:s.day,totalRevenue:0};const c=s.commerce;c.orders??=[];c.outside??={version:1,sinceDay:s.day,day:s.day,base:Object.fromEntries(Object.entries(base).map(([g,p])=>[g,p*2.4])),quota:100,privateExport:true,importEnabled:true,pressure:{},sold:{},spent:0,budget:180,totalPaid:0,totalImported:0};if(!c.outside.version){c.outside.base=Object.fromEntries(Object.entries(base).map(([g,p])=>[g,p*2.4]));c.outside.version=1;}return c;}
  function entry(s){const c=s.commerce;let d=c.days.find(d=>d.day===s.day);if(!d){d={day:s.day,levy:{},exported:{},aid:{},revenue:0};c.days.push(d);c.days=c.days.slice(-60);}return d;}
  function price(s,b,good,base){const c=ensure(s,base);return c.prices[good]*(b.enterprise?.priceFactor||1)*(b.id==='market2'?1.15:b.type==='dock'?1.45:1);}
  function openMarket(s){const o=s.commerce.outside;if(o.day!==s.day){const elapsed=s.day-o.day;for(const g of Object.keys(o.pressure))o.pressure[g]=Math.max(0,o.pressure[g]-demand[g]*.65*elapsed);o.day=s.day;o.sold={};o.spent=0;}return o;}
  function quote(s,good){const o=s.commerce.outside;return (o.base[good]||s.commerce.prices[good])*.85/(1+(o.pressure[good]||0)/demand[good]);}
  function capacity(s,good){const o=s.commerce.outside;return Math.max(0,demand[good]*o.quota/100-(o.day===s.day?o.sold[good]||0:0));}
  function sellOutside(s,good,amount,minPrice=0){const o=openMarket(s);if(s.incidents.some(e=>e.type==='blockade'&&e.status==='active'))return{amount:0,revenue:0};const n=Math.max(0,Math.min(amount,capacity(s,good))),a=(o.base[good]||s.commerce.prices[good])*.85*demand[good],h=demand[good]+(o.pressure[good]||0),budget=Math.max(0,o.budget-o.spent);
    // Integral of the descending demand curve: splitting a shipment cannot evade saturation.
    const sold=Math.max(0,Math.min(n,minPrice>0?a/minPrice-h:Infinity,h*Math.expm1(Math.min(50,budget/a)))),revenue=a*Math.log1p(sold/h);o.pressure[good]=(o.pressure[good]||0)+sold;o.sold[good]=(o.sold[good]||0)+sold;o.spent+=revenue;o.totalPaid+=revenue;return{amount:sold,revenue};}
  function produce(s,b,good,amount){const c=s.commerce,levy=c.levyEnabled?amount*c.levyRate/100:0;b.stock[good]+=amount-levy;c.stock[good]+=levy;if(levy){const d=entry(s);d.levy[good]=(d.levy[good]||0)+levy;b.cityLevy??={};b.cityLevy[good]=(b.cityLevy[good]||0)+levy;}}
  function exportFloor(s,b){const r=s.productionRecipe(b);return r?(Object.entries(r.inputs).reduce((n,[g,a])=>n+s.commerce.prices[g]*a,0))/r.amount/(1-(s.commerce.levyEnabled?s.commerce.levyRate:0)/100)/(1-Finance.rate(s,'export')/100):0;}
  function updatePrices(s,base,types){const c=s.commerce,goods=s.goods,pop=Math.max(12,s.alive.length),targets={bread:pop*1.2,fish:pop*.65,grain:pop*1.2,flour:pop*.85,wood:pop*.8,tools:pop*.35,wool:pop*.4,cloth:pop*.3,clothes:pop*.25,planks:pop*.5,furniture:pop*.15,coal:pop*.45,iron:pop*.4,clay:pop*.4,pottery:pop*.25};for(const[g,p]of Object.entries(base)){const scarcity=clamp(Math.sqrt((targets[g]+5)/(goods[g]+5)),.65,1.8);const producer=s.buildings.find(b=>types?.[b.type]?.recipe?.out===g),r=producer&&types[producer.type].recipe,retention=(s.commerce.levyEnabled?1-s.commerce.levyRate/100:1)*Math.min(1-Finance.rate(s,'sales')/100,.85*(1-Finance.rate(s,'export')/100));const cost=r?(producer.wage*r.time/60*1.3+Object.entries(r.inputs).reduce((n,[k,v])=>n+c.prices[k]*v,0))/r.amount/retention:0;const target=Math.max(p*scarcity,cost*1.12);c.prices[g]=round(clamp(c.prices[g]*.65+target*.35,p*.6,Math.max(p*3,cost*1.4)));}}
  function relief(s){const c=s.commerce,d=entry(s);let delivered=0;const homes=s.buildings.filter(b=>b.type==='home').map(b=>({b,people:s.alive.filter(p=>p.homeId===b.id)})).filter(x=>x.people.length).sort((a,b)=>a.b.stock.bread+a.b.stock.fish-b.b.stock.bread-b.b.stock.fish);
    for(const {b,people}of homes){if(b.stock.bread+b.stock.fish>=people.length||!people.some(p=>p.hunger<45||p.coins<2))continue;let need=Math.ceil(people.length*1.5-b.stock.bread-b.stock.fish);for(const g of ['bread','fish']){const n=Math.min(need,Math.floor(c.stock[g]+1e-8));if(n<=0)continue;c.stock[g]=Math.max(0,c.stock[g]-n);b.stock[g]+=n;need-=n;delivered+=n;d.aid[g]=(d.aid[g]||0)+n;}}
    if(delivered)s.log(`Из городского резерва доставлено ${delivered} порций еды семьям без припасов.`,'food',null,{title:'Помощь из городского склада',buildingId:'hall'});return delivered;
  }
  function exportGoods(s){const c=s.commerce;if(!c.autoExport||s.incidents.some(e=>e.type==='blockade'&&e.status==='active'))return 0;const d=entry(s);let revenue=0;const sold={};for(const[g,amount]of Object.entries(c.stock)){let n=amount;if(['bread','fish'].includes(g))n=Math.min(n,Math.max(0,s.food-s.alive.length*c.reserveDays));n=Math.floor(n*100)/100;if(n<=0)continue;const deal=sellOutside(s,g,n);n=deal.amount;if(n<=0)continue;c.stock[g]=Math.max(0,c.stock[g]-n);revenue+=deal.revenue;sold[g]=round(n);d.exported[g]=(d.exported[g]||0)+n;}if(revenue){s.changeTreasury(revenue,'cityExport');c.totalRevenue+=revenue;d.revenue+=revenue;c.history.unshift({day:s.day,revenue:round(revenue),sold});c.history=c.history.slice(0,30);s.log(`Город продал за пределы ${Object.entries(sold).map(([g,n])=>s.goodName(g).toLowerCase()+' '+n).join(', ')}. В казну поступило ${revenue.toFixed(1)} тал.`,'economy',null,{title:'Городской экспорт',buildingId:'dock'});}return revenue;}
  function order(s,buyer,seller,good,amount){const c=s.commerce,old=c.orders.find(o=>o.buyer===buyer.id&&o.seller===seller.id&&o.good===good);if(old)return true;if(seller.cash>=10||!s.canProduce(seller)||!s.productionRecipe(seller)||s.productionRecipe(seller).out!==good)return false;const cost=amount*s.price(seller,good);if(buyer.cash<cost)return false;buyer.cash-=cost;Finance.sale(s,seller,cost);const order={buyer:buyer.id,seller:seller.id,good,amount,paid:cost,unitPrice:cost/amount,at:s.now};c.orders.push(order);Agreements.supply(s,order);s.log(`${buyer.name} оплатил заранее ${amount} ед. ${s.goodName(good).toLowerCase()} у ${seller.name}. Поставщик получил оборотные средства.`,'economy',null,{title:'Заказ сырья с предоплатой',buildingId:seller.id});return true;}
  function credit(s,buyer,seller,good,amount,consume=false){const c=s.commerce,o=c.orders.find(o=>o.buyer===buyer.id&&o.seller===seller.id&&o.good===good);if(!o)return 0;const used=Math.min(o.amount,amount);if(consume){Agreements.delivered(s,o,used);o.paid=Math.max(0,o.paid-used*(o.unitPrice||s.price(seller,good)));o.amount-=used;c.orders=c.orders.filter(o=>o.amount>1e-8);}return used;}
  function configure(s,data){const rate=Number(data.levyRate),reserve=Number(data.reserveDays);if(!Number.isFinite(rate)||rate<0||rate>30||!Number.isFinite(reserve)||reserve<1||reserve>6)return{ok:false,message:'Натуральный сбор: 0–30%, резерв еды: 1–6 дней'};Object.assign(s.commerce,{levyEnabled:data.levyEnabled===true&&rate>0,levyRate:rate,autoExport:data.autoExport===true,reserveDays:reserve});s.log(`Правительство: натуральный сбор ${s.commerce.levyEnabled?rate+'% выпуска':'отменён'}, городской экспорт ${s.commerce.autoExport?'разрешён':'приостановлен'}, резерв еды ${reserve} порц. на жителя.`,'politics',null,{title:'Указ о городском снабжении',buildingId:'hall'});return{ok:true,message:'Правила применены к будущему выпуску. Экспорт проводится утром.'};}
  function productionLimits(s,types){const needs={bread:s.alive.length*.85,fish:s.alive.length*.3,clothes:s.alive.length*.04,pottery:s.alive.length*.03,furniture:s.alive.length*.02,tools:s.alive.length*.03},counts={};for(const b of s.buildings){const r=types[b.type]?.recipe;if(!r||b.construction)continue;counts[r.out]=(counts[r.out]||0)+1;for(const[g,n]of Object.entries(r.inputs))needs[g]=(needs[g]||0)+n*Math.max(1,s.workers(b.id).length)*180/r.time;}for(const b of s.buildings){const r=types[b.type]?.recipe;if(r&&b.enterprise)b.enterprise.stockLimit=Math.max(r.amount*4,((needs[r.out]||0)+demand[r.out]*.65)*2/(counts[r.out]||1));}}
  function configureOutside(s,data){const quota=Number(data.quota);if(!Number.isFinite(quota)||quota<0||quota>100)return{ok:false,message:'Квота внешних продаж: 0–100%'};Object.assign(s.commerce.outside,{quota,privateExport:data.privateExport===true,importEnabled:data.importEnabled===true});return{ok:true,message:'Указ действует на городской и частный экспорт. Уже оплаченные поставки сохранены.'};}
  function daily(s,base,types){const c=ensure(s,base);if(c.lastDay===s.day)return;c.lastDay=s.day;openMarket(s);updatePrices(s,base,types);productionLimits(s,types);relief(s);exportGoods(s);}
  function load(s,base){const c=ensure(s,base);if(!Number.isFinite(c.levyRate)||c.levyRate<0||c.levyRate>30||!Number.isFinite(c.reserveDays)||c.reserveDays<1||c.reserveDays>6||!Array.isArray(c.orders)||!c.orders.every(o=>s.building(o.buyer)&&s.building(o.seller)&&o.good in base&&Number.isFinite(o.amount)&&o.amount>0&&Number.isFinite(o.paid)&&o.paid>=0)||!Array.isArray(c.days)||!Array.isArray(c.history)||!Object.keys(base).every(k=>Number.isFinite(c.stock?.[k])&&c.stock[k]>=0&&Number.isFinite(c.prices?.[k])&&c.prices[k]>0))throw Error('Некорректное городское хозяйство');const o=c.outside,finite=n=>Number.isFinite(n)&&n>=0;if(!finite(o.quota)||o.quota>100||!finite(o.spent)||o.spent>o.budget+1e-6||!finite(o.budget)||!finite(o.day)||o.day>s.day||!finite(o.totalPaid)||!finite(o.totalImported)||!Object.values(o.pressure).every(finite)||!Object.values(o.sold).every(finite)||!Object.keys(base).every(g=>finite(o.base[g])&&o.base[g]>0)||typeof o.privateExport!=='boolean'||typeof o.importEnabled!=='boolean')throw Error('Некорректный внешний рынок');}
  const api={ensure,price,quote,capacity,sellOutside,exportFloor,productionLimits,openMarket,configureOutside,demand,produce,order,credit,updatePrices,relief,exportGoods,configure,daily,load};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.DanzigCommerce=api;
})(typeof window!=='undefined'?window:globalThis);
