(function(root){
 'use strict';
 const node=typeof module!=='undefined'&&module.exports,S=node?require('./social-life.js'):root.DanzigSocial,P=node?require('./personality.js'):root.DanzigPersonality,L=node?require('./learning.js'):root.DanzigLearning;
 const kinds={crime:'Правонарушение',loan:'Личный долг',supply:'Оплаченная поставка',wage:'Заработная плата',rent:'Арендный платёж'},statuses={petition:'Ожидает заявления',scheduled:'Назначено заседание',judged:'Приговор к исполнению',closed:'Завершено'},outcomes={acquittal:'Оправдание',warning:'Предупреждение',restitution:'Возмещение',fine:'Штраф и возмещение',service:'Общественные работы и возмещение'};
 const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),live=p=>p?.alive&&!p.absence&&!p.arriving,here=(p,id='hall')=>live(p)&&p.location===id&&!p.path.length;
 function ensure(s){return s.court??={version:1,lastDay:s.day,nextId:1,nextWage:1,cases:[],wages:[],history:[],totals:{filed:0,hearings:0,closed:0,recovered:0,fines:0,recusals:0,complaints:0}};}
 function note(s,c,text){const v=ensure(s);v.history.unshift({at:s.now,id:c.id,text});v.history=v.history.slice(0,80);s.log(text,'politics',c.judgeId||c.plaintiffId,{title:kinds[c.kind],buildingId:'hall',courtId:c.id});}
 function source(s,c){return c.kind==='crime'?s.civic.cases.find(x=>x.id===c.sourceId):c.kind==='wage'?ensure(s).wages.find(x=>x.id===c.sourceId):c.kind==='rent'?s.properties?.leases.find(x=>x.id===c.sourceId):s.agreements.items.find(x=>x.id===c.sourceId);}
 function remaining(s,c){const x=source(s,c);if(!x)return 0;if(c.kind==='crime')return Math.max(0,x.amount-x.recovered);if(c.kind==='rent')return Math.max(0,x.arrears);return Math.max(0,x.remaining);}
 function offer(s,kind,sourceId,plaintiffId,defendantId,buildingId=null){
  const v=ensure(s);if(!kinds[kind]||!s.person(plaintiffId)?.alive||!s.person(defendantId)?.alive||plaintiffId===defendantId)return null;
  const old=v.cases.find(c=>c.kind===kind&&c.sourceId===sourceId);if(old&&!(kind==='rent'&&old.status==='closed'&&s.now-old.opened>14*1440))return old;if(v.cases.filter(c=>c.status!=='closed').length>=60)return null;
  const c={id:v.nextId++,kind,sourceId,plaintiffId,defendantId,buildingId,opened:s.now,status:'petition',filedAt:null,judgeId:null,officerId:null,hearingAt:null,startedAt:null,postponed:0,summons:[],statements:[],recusals:[],verdict:null,paid:0,finesPaid:0,serviceApplied:false,complaint:null,reason:'Заявитель решает, обращаться ли в суд'};v.cases.unshift(c);v.cases=v.cases.filter(c=>c.status!=='closed').concat(v.cases.filter(c=>c.status==='closed').slice(0,100));return c;
 }
 function fromCrime(s,x){if(!x?.reported||x.status!=='open')return null;const c=offer(s,'crime',x.id,x.victimId,x.actorId,x.buildingId);if(c)x.courtId=c.id;return c;}
 function wage(s,p,b,amount){const v=ensure(s);if(!Number.isFinite(amount)||amount<=0)return;let x=v.wages.find(x=>x.personId===p.id&&x.buildingId===b.id&&x.remaining>0);if(!x){if(v.wages.filter(x=>x.remaining>0).length>=120)return false;x={id:v.nextWage++,personId:p.id,buildingId:b.id,at:s.now,amount:0,remaining:0,paid:0};v.wages.push(x);v.wages=v.wages.filter(x=>x.remaining>0||x===v.wages.at(-1)).concat(v.wages.filter(x=>x.remaining<=0&&x!==v.wages.at(-1)).slice(-60));}x.amount+=amount;x.remaining+=amount;return true;}
 function withhold(s,p,b,gross){const owner=s.person(b.ownerId);if(!owner?.alive||owner.id===p.id||owner.character?.values.honesty>=.2||owner.mind.personality.ambition<=.75||s.day-(b.lastWithheldDay??-4)<3)return gross;const held=gross*.5;if(!wage(s,p,b,held))return gross;b.lastWithheldDay=s.day;s.remember(p,'unpaid',b.id,'Работа выполнена, но часть заработка удержана; есть запись о долге.',-8);return gross-held;}
 function interested(s,p,c){const a=s.person(c.plaintiffId),b=s.person(c.defendantId);return !live(p)||p.age<25||[a?.id,b?.id].includes(p.id)||S.kin(p,a)||S.kin(p,b)||c.complaint?.judgeId===p.id;}
 function assign(s,c){
  const ids=[s.government.offices.judge?.personId,s.mayorId,s.government.offices.treasurer?.personId,...Object.values(s.government.offices).map(x=>x.personId)];
  for(const id of [...new Set(ids.filter(Boolean))]){const p=s.person(id);if(interested(s,p,c)){if(live(p)&&!c.recusals.some(r=>r.personId===id)){c.recusals.push({personId:id,at:s.now,reason:'Родство, личное участие или пересмотр собственного решения'});ensure(s).totals.recusals++;}continue;}if(c.judgeId!==id){c.startedAt=null;if(c.hearingAt)c.summons.push({personId:id,at:s.now,hearingAt:c.hearingAt});}c.judgeId=id;return p;}c.judgeId=null;c.reason='Нет доступного незаинтересованного члена магистрата';return null;
 }
 function schedule(s,c){const v=ensure(s);let day=s.day+1,hour=600;while(v.cases.some(x=>x!==c&&x.status==='scheduled'&&x.hearingAt===day*1440+hour)){hour+=150;if(hour>1050){day++;hour=600;}}c.hearingAt=day*1440+hour;c.startedAt=null;c.status='scheduled';assign(s,c);for(const id of [c.plaintiffId,c.defendantId,c.judgeId,...(c.kind==='crime'?source(s,c)?.witnesses||[]:[])])if(id&&live(s.person(id)))c.summons.push({personId:id,at:s.now,hearingAt:c.hearingAt});c.summons=c.summons.slice(-48);c.reason='Повестки вручены присутствующим в городе; заседание в ратуше';}
 function file(s,p,c){if(!c||c.status!=='petition'||c.plaintiffId!==p.id||!here(p)||s.conclusion)return{ok:false,message:'Заявление подаётся лично в ратуше.'};c.filedAt=s.now;ensure(s).totals.filed++;schedule(s,c);note(s,c,p.name+' подал заявление: '+kinds[c.kind].toLowerCase()+'.');return{ok:true};}
 function witnessIds(s,c){return c.kind==='crime'?(source(s,c)?.witnesses||[]):[];}
 function testify(s,p,c){if(!here(p)||![c.plaintiffId,c.defendantId,...witnessIds(s,c)].includes(p.id)||c.statements.some(x=>x.personId===p.id))return;const role=p.id===c.plaintiffId?'plaintiff':p.id===c.defendantId?'defendant':'witness',honest=(p.character?.values.honesty??.5)>=.3||S.trust(s,p,s.person(c.defendantId))<30;c.statements.push({personId:p.id,at:s.now,role,support:role==='plaintiff'||role==='witness'&&honest,text:role==='plaintiff'?'Подтверждает заявление и требует рассмотрения':role==='defendant'?'Просит учитывать обстоятельства и доступные средства':honest?'Подтверждает лично увиденное':'Отказывается подтвердить обвинение против знакомого'});}
 function proof(s,c){const x=source(s,c),testimony=c.statements.filter(t=>t.support),written=c.kind!=='crime'&&remaining(s,c)>1e-7;return {score:written?.95:Math.min(1,(testimony.some(t=>t.role==='plaintiff')?.25:0)+testimony.filter(t=>t.role==='witness').length*.35+(x?.kind==='brawl'?.35:0)),written};}
 function decide(s,c,judge,procedure='Очное заседание'){
  const v=judge.character.values,m=judge.mind.personality,e=proof(s,c),friendship=(S.trust(s,judge,s.person(c.defendantId))-S.trust(s,judge,s.person(c.plaintiffId)))/100,favour=friendship*(1-v.honesty)*.24,threshold=.38+v.justice*.2;
  let kind=e.score-favour<threshold?'acquittal':c.kind!=='crime'?'restitution':remaining(s,c)<.01&&m.empathy>.6?'warning':v.justice>.72?'service':'fine';
  const convicted=!['acquittal','warning'].includes(kind),x=source(s,c),fine=kind==='fine'?(x?.kind==='brawl'?12:8):0,service=kind==='service'?(x?.kind==='brawl'?180:90):0;
  return {kind,judgeId:judge.id,at:s.now,procedure,compensation:convicted?remaining(s,c):0,fine,service,reasons:[e.written?'Исследована запись действующего обязательства':'Заслушаны заявитель и '+c.statements.filter(x=>x.role==='witness').length+' свидетелей',Math.abs(favour)>.06?'Личные отношения повлияли на оценку судьи':'Судья опирается на известные обстоятельства',v.justice>.72?'Принципиальность усиливает строгость решения':m.empathy>.6?'Сочувствие смягчает подход':'Выбрано соразмерное взыскание'],bias:favour};
 }
 function adjudicate(s,c,judge){
  if(c.status!=='scheduled'||judge?.id!==c.judgeId||interested(s,judge,c)||!here(judge)||s.now<c.hearingAt||s.now>c.hearingAt+120)return false;
  const plaintiff=s.person(c.plaintiffId),defendant=s.person(c.defendantId);if(!here(plaintiff))return false;
  const defaultAllowed=c.kind!=='crime'&&c.postponed>=2&&live(defendant)&&!defendant.sick&&defendant.hunger>=15&&c.summons.filter(x=>x.personId===defendant.id).length>=2&&proof(s,c).written;
  if(!here(defendant)&&!defaultAllowed){c.startedAt=null;return false;}testify(s,plaintiff,c);if(here(defendant))testify(s,defendant,c);for(const id of witnessIds(s,c))testify(s,s.person(id),c);
  c.startedAt??=s.now;if(s.now-c.startedAt<30)return false;
  c.verdict=decide(s,c,judge,here(defendant)?'Очное заседание':'Заочное гражданское решение после двух вручённых повесток и неявок');c.status=['acquittal','warning'].includes(c.verdict.kind)?'closed':'judged';c.reason=c.verdict.reasons.join('. ');c.nextEnforcement=s.day+4;ensure(s).totals.hearings++;if(c.status==='closed')ensure(s).totals.closed++;
  if(c.kind==='crime'){const x=source(s,c);if(x){x.status=c.status==='closed'?'closed':'solved';x.resolvedDay=s.day;if(x.status==='solved'&&!c.countedConviction){s.civic.totals.solved++;c.countedConviction=true;}}}
  note(s,c,judge.name+': '+outcomes[c.verdict.kind]+'. '+c.reason+'.');return true;
 }
 function payer(s,c){return ['supply','wage'].includes(c.kind)?{object:s.building(c.kind==='supply'?source(s,c)?.sellerId:source(s,c)?.buildingId),key:'cash',reserve:12}:c.kind==='rent'&&source(s,c)?.use==='workshop'?{object:s.building(source(s,c).buildingId),key:'cash',reserve:12}:{object:s.person(c.defendantId),key:'coins',reserve:12};}
 function pay(s,c,limit=Infinity){
  if(c.status!=='judged'||!c.verdict)return 0;const from=payer(s,c),x=source(s,c);if(!x||!from.object)return 0;let amount=Math.min(remaining(s,c),Math.max(0,c.verdict.compensation-c.paid),Math.max(0,from.object[from.key]-from.reserve),limit);const recipient=c.kind==='supply'?s.building(x.buyerId):s.person(c.plaintiffId);if(!recipient)return 0;
  from.object[from.key]-=amount;if(c.kind==='wage')s.payCourtWage(recipient,amount,from.object);else recipient[c.kind==='supply'?'cash':'coins']+=amount;c.paid+=amount;ensure(s).totals.recovered+=amount;
  if(c.kind==='crime'){x.recovered+=amount;s.civic.totals.recovered+=amount;}else if(c.kind==='rent'){s.recordHouseholdIncome?.(recipient,amount);x.arrears=Math.max(0,x.arrears-amount);x.paid+=amount;}else{x.remaining=Math.max(0,x.remaining-amount);if(c.kind==='supply'){x.refunded+=amount;const o=s.commerce.orders.find(o=>o.agreementId===x.id);if(o){o.amount=Math.max(0,o.amount-amount/x.unitPrice);o.paid=Math.max(0,o.paid-amount);if(x.remaining<1e-7)s.commerce.orders=s.commerce.orders.filter(y=>y!==o);}if(from.object.enterprise)from.object.enterprise.openingCash-=amount;if(recipient.enterprise)recipient.enterprise.openingCash+=amount;}else{x.paid+=amount;if(c.kind==='loan')s.agreements.repaid+=amount;}if(x.remaining<1e-7&&c.kind!=='wage')x.status='fulfilled';}
  const fine=Math.min(Math.max(0,c.verdict.fine-c.finesPaid),Math.max(0,from.object[from.key]-from.reserve),Math.max(0,limit-amount));from.object[from.key]-=fine;if(fine)s.changeTreasury(fine,'crimeFines');c.finesPaid+=fine;ensure(s).totals.fines+=fine;if(c.kind==='crime'){s.civic.totals.fines+=fine;x.fine+=fine;}
  if(!c.serviceApplied){const p=s.person(c.defendantId);p.civic.service+=c.verdict.service;c.serviceApplied=true;if(c.kind==='crime'){p.reputation=Math.max(0,p.reputation-8);P.event(s,p,'punished',c.plaintiffId,'Решение судьи: '+outcomes[c.verdict.kind],22);L.observe(s,p,{goal:'civicOffence',title:'Правонарушение',steps:[]},false,'Личный суд завершился наказанием');}}
  if((remaining(s,c)<1e-7||c.paid>=c.verdict.compensation-1e-7)&&c.finesPaid>=c.verdict.fine-1e-7){c.status='closed';ensure(s).totals.closed++;c.reason='Денежные требования исполнены; назначенные работы учитываются отдельно';}return amount+fine;
 }
 function officer(s,c){if(live(s.person(c.officerId)))return s.person(c.officerId);const candidate=[s.person(s.government.offices.captain?.personId),...s.alive.filter(p=>p.age>=25)].find(p=>live(p)&&![c.plaintiffId,c.defendantId,c.judgeId].includes(p.id)&&!S.kin(p,s.person(c.defendantId)));c.officerId=candidate?.id||null;return candidate;}
 function enforce(s,p,c){const from=c&&payer(s,c),where=from?.key==='cash'?from.object?.id:p.location;if(!c||c.status!=='judged'||(c.nextEnforcement??0)>s.day||officer(s,c)?.id!==p.id)return{ok:false,message:'Решение ещё нельзя исполнять.'};if(!here(p,where)||from.key==='coins'&&!here(s.person(c.defendantId),where)){c.nextEnforcement=s.day+1;return{ok:false,message:'Плательщик отсутствует; пристав повторит визит.'};}const amount=pay(s,c);c.nextEnforcement=s.day+2;note(s,c,p.name+' исполняет решение судьи: взыскано '+amount.toFixed(1)+' тал. Остаток не списан.');return{ok:true};}
 function appeal(s,p,c){if(!c?.verdict||c.complaint||c.paid>0||c.finesPaid>0||c.serviceApplied||![c.plaintiffId,c.defendantId].includes(p.id)||!here(p)||s.now-c.verdict.at>4*1440||Math.abs(c.verdict.bias)<.06)return{ok:false,message:'Нет оснований или срок жалобы истёк.'};c.complaint={personId:p.id,judgeId:c.verdict.judgeId,at:s.now,previous:JSON.parse(JSON.stringify(c.verdict))};ensure(s).totals.complaints++;c.verdict=null;schedule(s,c);note(s,c,p.name+' подал жалобу на личную заинтересованность судьи; назначен пересмотр другим членом магистрата.');return{ok:true};}
 function tick(s){for(const c of ensure(s).cases.filter(c=>c.status==='scheduled')){if(interested(s,s.person(c.judgeId),c))assign(s,c);if(s.now>c.hearingAt+120){c.postponed++;if(c.postponed>=8){c.status='closed';c.reason='Рассмотрение прекращено без приговора: стороны не смогли явиться';if(c.kind==='crime'&&source(s,c))source(s,c).status='closed';}else schedule(s,c);continue;}const judge=s.person(c.judgeId);if(judge&&judge.plan?.steps[judge.plan.index]?.courtId===c.id)adjudicate(s,c,judge);}}
 function daily(s){const v=ensure(s);if(v.lastDay>=s.day)return;v.lastDay=s.day;
  for(const a of s.agreements.items)if(a.status==='overdue'&&a.remaining>0){if(a.kind==='loan')offer(s,'loan',a.id,a.lenderId,a.borrowerId);if(a.kind==='supply')offer(s,'supply',a.id,s.building(a.buyerId)?.ownerId,s.building(a.sellerId)?.ownerId,a.sellerId);}
  for(const w of v.wages)if(w.remaining>0&&s.now-w.at>=1440)offer(s,'wage',w.id,w.personId,s.building(w.buildingId)?.ownerId,w.buildingId);
  for(const l of s.properties?.leases||[])if(l.arrears>l.rate*3){const owner=s.propertyOwner(s.building(l.buildingId));if(owner)offer(s,'rent',l.id,owner.id,l.tenantId,l.buildingId);}
  for(const c of v.cases){if(c.status==='petition'&&s.now-c.opened>30*1440){c.status='closed';c.reason='Заявитель не обратился в суд';if(c.kind==='crime'&&source(s,c))source(s,c).status='closed';}if(c.status==='judged')officer(s,c);if(c.status!=='closed'&&(!s.person(c.plaintiffId)?.alive||!s.person(c.defendantId)?.alive)){c.status='closed';c.reason='Сторона умерла; производство прекращено без нового взыскания';if(c.kind==='crime'&&source(s,c)){source(s,c).status='closed';source(s,c).resolvedDay=s.day;}}}
 }
 function candidates(s,p,add,step){if(!live(p)||p.age<16||p.hunger<18||p.energy<15||s.hour<7||s.hour>=20)return;const v=ensure(s),active=v.cases.filter(c=>c.status==='scheduled'&&[c.judgeId,c.plaintiffId,c.defendantId,...witnessIds(s,c)].includes(p.id)&&s.now>=c.hearingAt-180&&s.now<=c.hearingAt+120).sort((a,b)=>a.hearingAt-b.hearingAt)[0];
  if(active){add('courtAttend',p.id===active.judgeId?'Провести судебное заседание':'Явиться по судебной повестке',112,'Дело №'+active.id+': '+kinds[active.kind]+'. Необходимо личное присутствие.',[step('courtAttend','hall','Участвовать в заседании',{duration:Math.max(45,active.hearingAt+120-s.now),courtId:active.id})]);return;}
  const petition=v.cases.find(c=>c.status==='petition'&&c.plaintiffId===p.id);if(petition)add('courtFile','Подать заявление в суд',63+(p.character.values.justice-.5)*20,'Просьба о разбирательстве будет рассмотрена конкретным судьёй',[step('courtFile','hall','Передать заявление',{duration:20,courtId:petition.id})]);
  const order=v.cases.find(c=>c.status==='judged'&&(c.nextEnforcement??0)<=s.day&&c.officerId===p.id);if(order){const from=payer(s,order),def=s.person(order.defendantId),target=from.key==='cash'?from.object.id:here(def,p.location)?p.location:s.hour>=8&&s.hour<18&&def.jobId?def.jobId:def.homeId;add('courtEnforce','Исполнить судебное решение',104+Math.min(16,Math.max(0,s.now-order.verdict.at)/1440),'Посетить плательщика по исполнительному листу №'+order.id,[step('courtEnforce',target,'Предъявить исполнительный лист',{duration:25,courtId:order.id})]);}
  const complaint=v.cases.find(c=>c.verdict&&!c.complaint&&Math.abs(c.verdict.bias)>.06&&s.now-c.verdict.at<=4*1440&&[c.plaintiffId,c.defendantId].includes(p.id));if(complaint&&p.character.values.justice>.65)add('courtAppeal','Обжаловать пристрастное решение',68,'Личные отношения судьи могли повлиять на исход',[step('courtAppeal','hall','Подать жалобу',{duration:20,courtId:complaint.id})]);
 }
 function execute(s,p,step){const c=ensure(s).cases.find(c=>c.id===step.courtId);if(step.kind==='courtFile')return file(s,p,c);if(step.kind==='courtEnforce')return enforce(s,p,c);if(step.kind==='courtAppeal')return appeal(s,p,c);return{ok:!!c};}
 function load(s){const v=ensure(s),n=x=>Number.isFinite(x)&&x>=0,id=x=>Number.isInteger(x)&&x>0;if(v.version!==1||!id(v.nextId)||!id(v.nextWage)||!n(v.lastDay)||v.lastDay>s.day||!Array.isArray(v.cases)||v.cases.length>160||!Array.isArray(v.wages)||v.wages.length>180||!Array.isArray(v.history)||v.history.length>80||!Object.values(v.totals).every(n))throw Error('Некорректный судебный реестр');
  const ids=new Set();for(const c of v.cases){if(!id(c.id)||c.id>=v.nextId||ids.has(c.id)||!kinds[c.kind]||!statuses[c.status]||!s.person(c.plaintiffId)||!s.person(c.defendantId)||c.plaintiffId===c.defendantId||!['opened','postponed','paid','finesPaid'].every(k=>n(c[k]))||c.opened>s.now||c.judgeId!==null&&!s.person(c.judgeId)||c.officerId!==null&&!s.person(c.officerId)||!Array.isArray(c.summons)||c.summons.length>48||c.summons.some(x=>!s.person(x.personId)||!n(x.at)||!n(x.hearingAt))||!Array.isArray(c.statements)||c.statements.some(x=>!s.person(x.personId)||!['plaintiff','defendant','witness'].includes(x.role)||typeof x.support!=='boolean')||!Array.isArray(c.recusals)||c.verdict&&(!outcomes[c.verdict.kind]||!s.person(c.verdict.judgeId)||!['at','compensation','fine','service'].every(k=>n(c.verdict[k])))||c.status==='scheduled'&&!n(c.hearingAt)||c.status==='judged'&&!c.verdict)throw Error('Некорректное судебное дело');ids.add(c.id);}
  const wages=new Set();for(const w of v.wages){if(!id(w.id)||w.id>=v.nextWage||wages.has(w.id)||!s.person(w.personId)||!s.building(w.buildingId)||!['amount','remaining','paid','at'].every(k=>n(w[k]))||Math.abs(w.remaining+w.paid-w.amount)>1e-6)throw Error('Некорректный долг по зарплате');wages.add(w.id);}for(const p of s.people)for(const step of p.plan?.steps||[])if(step.kind.startsWith('court')&&!ids.has(step.courtId))throw Error('Некорректная повестка');
 }
 const api={kinds,statuses,outcomes,ensure,source,remaining,offer,fromCrime,wage,withhold,assign,schedule,file,testify,proof,decide,adjudicate,pay,officer,enforce,appeal,tick,daily,candidates,execute,load};if(node)module.exports=api;else root.DanzigCourt=api;
})(typeof window!=='undefined'?window:globalThis);
