(function(root){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=n=>Number(n||0).toLocaleString('ru-RU',{maximumFractionDigits:1});
  const D=()=>root.DanzigDevelopment,G=()=>root.DanzigGovernment;
  function ownerName(s,b){return D().owner(s,b)?.name||'Пока нет владельца';}
  function project(s,b){const q=b.development?.project;if(!q)return'';const progress=Math.min(100,Math.max(0,(s.now-q.startedAt)/(q.until-q.startedAt)*100));return `<div class="upgrade-project"><b>${esc(q.name)}</b><span>${num(progress)}% · ещё ${num(Math.max(0,q.until-s.now)/1440)} дн.</span><progress max="100" value="${progress}" aria-label="Готовность улучшения"></progress><small>${esc(q.effect)} · оплачено ${num(q.cost)} тал.</small></div>`;}
  function building(s,b){const d=b.development;if(!d)return'';return `<section class="building-development"><div class="section-label">РАЗВИТИЕ ДВОРА <span>УРОВЕНЬ ${d.level} / 3</span></div><div class="level-steps" aria-label="Уровень здания">${[1,2,3].map(n=>`<span class="${n<=d.level?'reached':''}">${n===1?'I':n===2?'II':'III'}</span>`).join('')}</div><p>Решает: <b>${esc(ownerName(s,b))}</b></p>${project(s,b)||`<p>${esc(d.assessment)}</p>`}<div class="upgrade-extra-list">${D().EXTRAS[D().kind(s,b)].map(([name,effect],i)=>`<div class="${d.extras.includes(i+1)?'built':''}"><span>${d.extras.includes(i+1)?'✓':i+1>d.level?'◇':'○'} ${esc(name)}</span><small>Уровень ${i+1} · ${esc(effect)}${i<d.level&&!d.extras.includes(i+1)?' · '+D().options(s,b).find(o=>o.id==='extra'+(i+1))?.cost+' тал.':''}</small></div>`).join('')}</div><button class="minor-button" data-development>Магистрат и развитие дворов ↗</button></section>`;}
  function prices(){return '<h3>Стоимость и темп развития</h3><p>Переход на II уровень: 6 дней освоения и 6 дней работ. Переход на III: 24 дня на предыдущем уровне и 12 дней работ. После любого подряда нужен перерыв: 6 дней после перестройки, 3 после дополнения. Предприятия подтверждают доход за 6–12 дней, ратуша — положительный обычный бюджет.</p><div class="ledger-table-wrap"><table><thead><tr><th>Здание</th><th>II уровень</th><th>III уровень</th><th>Дополнения I / II / III</th></tr></thead><tbody>'+Object.entries({home:'Дом',production:'Производство',service:'Служба',hall:'Ратуша'}).map(([k,name])=>{const c=D().COSTS[k];return '<tr><td>'+name+'</td><td>'+num(c.second)+' тал.</td><td>'+num(c.third)+' тал.</td><td>'+[1,2,4].map(n=>num(c.extra*n)).join(' / ')+' тал.</td></tr>';}).join('')+'</tbody></table></div><p class="muted">Дополнения строятся 3 / 4 / 6 дней. Накопленные деньги не отменяют освоение ступени и проверку потребности. Оплаченные ранее подряды сохраняют договорную цену и срок.</p>';}
  function render(s){
    const h=s.building('hall'),l=D().level(h),next=D().options(s,h).find(o=>o.id==='level'),check=next&&D().assess(s,h,next),target=next&&D().HALL[next.level],v=s.development;
    const buildings=[...s.buildings].sort((a,b)=>Number(!!b.development.project)-Number(!!a.development.project)||D().level(b)-D().level(a));
    return `<section class="magistrate-hero"><div><span class="eyebrow">САМОУПРАВЛЕНИЕ · БЕЗ ВАШЕГО УЧАСТИЯ</span><h3>${D().HALL[l].name}</h3><p>Бургомистр развивает ратушу, совет избирает должностных лиц, владельцы заботятся о своих дворах. Каждое решение оплачивается из существующих средств.</p></div><div class="hall-seal"><small>УРОВЕНЬ</small><b>${['','I','II','III'][l]}</b><span>${Object.keys(s.government.offices).length} новых должностей</span></div></section>
      <div class="development-kpis"><div><small>Дворов выше I уровня</small><b>${s.buildings.filter(b=>D().level(b)>1).length}</b></div><div><small>Работы идут</small><b>${s.buildings.filter(b=>b.development.project).length}</b></div><div><small>Улучшений завершено</small><b>${v.completed}</b></div><div><small>Вложено всеми владельцами</small><b>${num(v.spent)} <small>тал.</small></b></div></div>
      <section class="hall-next"><div><span class="eyebrow">СЛЕДУЮЩАЯ СТУПЕНЬ</span><h3>${target?.name||'Высшая ступень достигнута'}</h3><p>${target?`${target.population} жителей · ${next.cost} тал. · ${next.days} дн. работ`:'Теперь город может развить все должности и все три уровня дворов.'}</p>${target?`<progress max="${target.population}" value="${Math.min(s.alive.length,target.population)}" aria-label="Население для развития ратуши"></progress><small>Население ${s.alive.length} / ${target.population} · свободно в казне ${num(D().funds(s,h))} тал. после резерва</small>`:''}</div><div>${project(s,h)||`<b>${check?.ok?'Бургомистр может оформить подряд':'Решение бургомистра'}</b><p>${esc(check?.message||h.development.assessment)}</p>`}<button class="quiet" id="development-review">Попросить владельцев оценить проекты</button><p class="muted">Они сами выберут полезные и посильные улучшения.</p></div></section>
      <div class="development-heading"><div><span class="eyebrow">КТО ПРИНИМАЕТ РЕШЕНИЯ</span><h3>Городской магистрат</h3></div><small>Мандат — 12 дней. Должность совмещается с ремеслом.</small></div>
      <div class="office-grid"><article class="office-card"><span class="office-tier">ДЕЙСТВУЕТ С I УРОВНЯ</span><h3>Бургомистр</h3><b>${esc(s.person(s.mayorId)?.name||'Вакантно')}</b><p>Развитие ратуши и общественных служб. До открытия новых должностей — также налоги и строительные разрешения.</p></article>${Object.entries(G().OFFICES).map(([key,o])=>{const locked=o.level>l,seat=s.government.offices[key],p=s.person(seat?.personId),manual=key==='treasurer'?!s.fiscal.autoMayor:s.government.manual[key];return `<article class="office-card ${locked?'locked':''}"><span class="office-tier">${locked?'ОТКРОЕТСЯ НА '+(o.level===2?'II':'III')+' УРОВНЕ':'ДЕЙСТВУЕТ С '+(o.level===2?'II':'III')+' УРОВНЯ'}</span><h3>${o.name}</h3><b>${locked?'Место ещё не учреждено':esc(p?.name||'Бургомистр исполняет обязанности')}</b><p>${o.power}.</p>${locked?'':`<span class="autonomy-state">${manual?'Закреплено вашим указом':'Решает самостоятельно'}</span><p class="office-decision">${esc(seat?.decision?.text||'Первая оценка — на ближайшем заседании.')}</p><button class="quiet" data-office-auto="${key}" data-enabled="${!!manual}">${manual?'Вернуть самостоятельность':'Зафиксировать настройки'}</button>`}</article>`;}).join('')}</div>
      <div class="development-heading"><div><span class="eyebrow">ЧАСТНЫЕ И ГОРОДСКИЕ ДВОРЫ</span><h3>Решения владельцев</h3></div><button class="quiet" id="development-auto">${v.auto?'Приостановить новые улучшения':'Возобновить самостоятельные улучшения'}</button></div><p>Уровень даёт больше места или повышает эффективность. На каждом уровне доступно отдельное улучшение. Семьи сохраняют по 60 талеров на взрослого, мастерские — 160 на оборот, гильдии — 80. Подрядчик включает материалы в цену; работы не останавливают двор.</p>
      ${prices()}<div class="ledger-table-wrap"><table class="development-table"><thead><tr><th>Двор / владелец</th><th>Уровень</th><th>Средства сверх резерва</th><th>Решение и работы</th></tr></thead><tbody>${buildings.map(b=>`<tr><td><button data-expansion-focus="${b.id}">${esc(b.name)}</button><small>${esc(ownerName(s,b))}</small></td><td><b>${D().level(b)} / 3</b><small>Дополнений: ${b.development.extras.length} / 3</small></td><td>${num(D().funds(s,b))} тал.</td><td>${project(s,b)||esc(b.development.assessment)}</td></tr>`).join('')}</tbody></table></div>
      <p id="development-result" role="status"></p><h3>Летопись решений и улучшений</h3><div class="development-history">${[...v.history,...s.government.history].sort((a,b)=>b.at-a.at).slice(0,30).map(e=>`<article><small>День ${Math.floor(e.at/1440)+1} · ${esc(s.person(e.personId)?.name||'Городской совет')}</small><p>${esc(e.text)}</p></article>`).join('')||'<p>Первые оценки появятся следующим утром. Новые должности откроются после завершения перестройки ратуши.</p>'}</div>`;
  }
  function bind(d){d.root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;let result;if(b.id==='development-review')result=d.sim.reviewDevelopment();if(b.id==='development-auto')result=d.sim.setDevelopmentAuto(!d.sim.development.auto);if(b.dataset.officeAuto)result=d.sim.setOfficeAutonomy(b.dataset.officeAuto,b.dataset.enabled==='true');if(result){d.changed();d.renderBody();const out=d.root.querySelector('#development-result');if(out)out.textContent=result.message;}});}
  root.DanzigDevelopmentView={building,render,bind};
})(window);
