(function(root){
  'use strict';
  const H=root.DanzigHousing,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=n=>Number(n||0).toLocaleString('ru-RU',{maximumFractionDigits:2});
  function render(d){const s=d.sim,v=H.ensure(s).land;
    return projects(d)+root.DanzigCivicView.homes()+root.DanzigTitlesView.render(d)+`<span class="eyebrow">РАЙОНЫ И СТОИМОСТЬ ЖИЛЬЯ</span><h3>Сословия и городская земля</h3><p>Простолюдины в основном живут в предместьях, ремесленные дома стоят рядом с мастерскими. Дворянский квартал дороже. Сословие наследуется в семье или повышается через пожалование титула; состоятельные жители с высокой репутацией тоже могут поселиться в дорогом квартале.</p><div class="ledger-kpis">${Object.entries(H.estates).map(([id,label])=>d.card(label,s.alive.filter(p=>p.estate===id).length,'Жители в городе')).join('')}${d.card('Аренда земли в казну',num(v.paid)+' тал.','За всё время учёта; льготы '+num(v.relief)+' тал.')}</div><p class="ledger-notice">Дома принадлежат семьям, земля под жильём — городу. Аренду платят присутствующие взрослые; первые 12 талеров защищены, непосильная часть получает льготу. Сбор с недвижимости отдельно оплачивает хозяйство. При тесноте или дорогом жилье семья ищет подходящий дом и переезжает по улицам.</p><div class="ledger-table-wrap"><table><thead><tr><th>Район</th><th>Жители</th><th>Мест в домах</th><th>Земельная аренда, тал./взрослого/день</th><th>Множитель сбора с двора</th></tr></thead><tbody>${Object.entries(root.DanzigWorld.Layout.districts).map(([id,q])=>{const homes=s.buildings.filter(b=>b.type==='home'&&b.district===id),people=s.alive.filter(p=>homes.some(b=>b.id===p.homeId));return `<tr><td>${esc(q.name)}</td><td>${people.length}</td><td>${homes.reduce((n,b)=>n+H.room(b),0)}</td><td>${num(q.rent)}</td><td>×${q.tax}</td></tr>`;}).join('')}</tbody></table></div><p class="muted">Аренда указана для I уровня: каждый следующий уровень повышает её на 25% базовой ставки. Отсутствующие на службе жители не платят за дни отсутствия. Накопленная аренда отражается в казне и в семейных расходах.</p><h3>Жилые дворы</h3><div class="ledger-table-wrap"><table><thead><tr><th>Дом</th><th>Квартал</th><th>Жители</th><th>Начислено сегодня</th><th>Уплачено сегодня</th></tr></thead><tbody>${s.buildings.filter(b=>b.type==='home').map(b=>{const people=s.alive.filter(p=>p.homeId===b.id),rows=people.map(p=>p.landRent).filter(r=>r?.day===s.day);return `<tr><td>${esc(b.name)}</td><td>${esc(H.district(b).name)}</td><td>${people.length} / ${H.room(b)}</td><td>${num(rows.reduce((n,r)=>n+r.due,0))}</td><td>${num(rows.reduce((n,r)=>n+r.paid,0))}</td></tr>`;}).join('')}</tbody></table></div>`;
  }
  function projects(d){const s=d.sim,rows=[...H.census(s).values()],plans=s.living.filter(p=>p.housingWish&&!p.housingWish.to&&!root.DanzigHousingProjects.current(s,H.movingFamily(s,p))),applications=root.DanzigHousingProjects.ensure(s).applications.filter(a=>['pending','building','ready'].includes(a.status));
    const status={pending:'Ратуша',building:'Строительство',ready:'Готов к заселению'};
    return '<span class="eyebrow">СВОЙ ДОМ</span><h3>Жильё и семейное строительство</h3><div class="ledger-kpis">'+d.card('Тесные дома',rows.filter(r=>r.present>r.capacity).length,'Занято больше комфортной вместимости')+d.card('Семьи ищут дом',plans.length,'Готового подходящего жилья пока нет')+d.card('Частные стройки',applications.filter(a=>a.status==='building').length,'Оплачены семейными сбережениями')+'</div><p class="ledger-notice">Семьи сначала ищут свободное жильё, затем копят на свой дом. Разрешение выдаёт '+(s.guilds.permitMode==='auto'?'бургомистр или сенешаль автоматически':'ратуша в ручном режиме')+'. Материалы и труд оплачиваются из семейной сметы. Еда, топливо и необходимая одежда имеют приоритет перед накоплениями. Готовый дом ждёт заказчиков.</p><div class="ledger-table-wrap"><table><thead><tr><th>Семья</th><th>Жильцов / мест</th><th>Решение</th><th>Состояние</th></tr></thead><tbody>'+plans.map(p=>{const r=rows.find(r=>r.b.id===p.homeId),q=p.homeProject;return '<tr><td>'+esc(p.surname)+'</td><td>'+r.members.length+' / '+r.capacity+'</td><td>Собственный дом</td><td>'+esc(q?.reason||'Подбираем участок')+'</td></tr>';}).join('')+applications.map(a=>{const p=s.person(a.personId),r=rows.find(r=>r.b.id===p?.homeId),b=s.building(a.lotId);return '<tr><td>'+esc(p?.surname||'Семья')+'</td><td>'+(r?r.members.length+' / '+r.capacity:'—')+'</td><td>'+status[a.status]+(b?' · '+esc(b.name):'')+'</td><td>'+esc(a.status==='building'?b?.construction?.local?.reason||a.reason:a.reason)+(a.status==='pending'&&s.guilds.permitMode==='manual'?'<div><button data-home-permit="'+a.id+'" data-allow="true">Разрешить</button> <button data-home-permit="'+a.id+'" data-allow="false">Отказать</button></div>':'')+'</td></tr>';}).join('')+'</tbody></table></div>'+(!plans.length&&!applications.length?'<p class="muted">Семейных заявок пока нет. Строительство начинается при нехватке подходящего жилья и наличии средств.</p>':'')+'<p id="housing-result" role="status"></p>';
  }
  function bind(d){d.root.addEventListener('click',e=>{const b=e.target.closest('[data-home-permit]');if(!b)return;const result=d.sim.decideHomePermit(b.dataset.homePermit,b.dataset.allow==='true');d.changed();d.renderBody();d.root.querySelector('#housing-result').textContent=result.message;});}
  root.DanzigDistrictView={render,projects,bind};
})(window);
