(function(root){
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function render(s){const G=root.DanzigGovernment,E=G.Elections,v=E.ensure(s),name=id=>esc(s.person(id)?.name||'Нет участника'),office=k=>G.OFFICES[k]?.name||'Бургомистр',stage={registration:'Регистрация',ballot:'Личное голосование',closed:'Завершено'},keys=E.keys(s),levels=s.building('hall').development.level;
  const tier=(list,label)=>`<section class="election-tier"><b>${label}</b><div>${list.map(k=>{const p=E.holder(s,k),acting=k==='mayor'?s.government.mayorSeat?.acting:s.government.offices[k]?.acting;return `<span><strong>${office(k)}</strong> · ${p?name(p.id):'Вакансия'}${acting?' · временно':''}</span>`;}).join('')}</div></section>`;
  return `<section class="elections-report"><h3>Ярусы и выборщики</h3>${tier(['mayor'],'Верхний ярус')}${tier(['judge','treasurer'],levels===1?'Нижний ярус':'Средний ярус')}${levels>1?tier(keys.filter(k=>E.rank(s,k)===2),'Нижний ярус'):''}<p>Бургомистра избирают ${E.electors(s,'mayor').length} нижестоящих чиновника. Судью и казначея избирает бургомистр; ${levels>1?'остальные должности — судья и казначей.':'после улучшения ратуши они будут избирать новые должности.'} Один человек — одно политическое место и один голос. Временный исполнитель действует до выборов.</p>
  <h3>Предстоящие заседания</h3>${v.active.length?v.active.map(e=>`<details class="election-session" open><summary>${office(e.office)} · ${stage[e.stage]} · тур ${e.round}</summary><p>До дня ${Math.floor(e.until/1440)+1}. Выборщики: ${e.electors.map(name).join(', ')}. Кандидаты: ${e.candidates.map(name).join(', ')||'Регистрация ещё идёт'}.</p>${ballots(e,name)}</details>`).join(''):'<p>Открытых выборов нет. Ближайшая регистрация: день '+(Math.min(...Object.values(v.next))+1)+'. Мандат — 24 дня, выборы разных мест проходят последовательно.</p>'}
  <h3>Бюллетени и результаты</h3>${v.archive.slice(0,8).map(e=>`<details class="election-session"><summary>${office(e.office)} · ${e.winner?name(e.winner):'Повторное заседание'} · день ${Math.floor(e.closed/1440)+1}</summary><p>${esc(e.reason)}</p>${ballots(e,name)}</details>`).join('')||'<p>Первые личные бюллетени появятся после заседания.</p>'}</section>`;
 }
 function ballots(e,name){return e.ballots.length?`<div class="ledger-table-wrap"><table><thead><tr><th>Тур</th><th>Выборщик</th><th>Голос</th><th>Причина</th></tr></thead><tbody>${e.ballots.map(b=>`<tr><td>${b.round}</td><td>${name(b.voterId)}</td><td>${b.candidateId?name(b.candidateId):'Воздержался'}</td><td>${esc(b.reason)}</td></tr>`).join('')}</tbody></table></div>`:'';}
 root.DanzigElectionView={render};
})(typeof window!=='undefined'?window:globalThis);
