(function(root){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),n=x=>Number(x||0).toLocaleString('ru-RU',{maximumFractionDigits:1}),sum=a=>a.reduce((a,b)=>a+b,0);
  function render(d){const s=d.sim,sites=root.DanzigConstruction.contracts(s),workshops=s.buildings.filter(b=>b.enterprise&&!b.construction),works=s.works;
    return `<div class="household-intro"><span class="eyebrow">ПРОИЗВОДСТВО И МЕСТНЫЕ ПОДРЯДЫ</span><h3>От покупателя до рабочего места</h3><p>Владелец сравнивает недавние продажи, заказы, себестоимость и запас денег. Заказы строек создают спрос на балки, гвозди и черепицу. Ассортимент и доступный найм пересматриваются утром.</p></div>
    <div class="ledger-kpis">${d.card('Действующих мастерских',workshops.length)}${d.card('Денег в подрядах',n(sum(sites.map(x=>x.q.cash)))+' тал.','Оплачены заказчиком; ещё не потрачены')}${d.card('Местным поставщикам',n(works.local)+' тал.','Закупки всех новых подрядов')}${d.card('Работникам строек',n(works.wages)+' тал.','Доставки и работа, до налогов')}</div>
    <h3>Решения предприятий</h3><div class="household-list">${workshops.map(b=>{const a=b.business,f=a?.forecast,book=(a?.days||[]).filter(x=>x.day>=s.day-6),total=k=>sum(book.map(x=>x[k]));return `<details class="household-family enterprise-card"><summary><span><b>${esc(b.name)}</b><small>${esc(s.goodName(s.productionRecipe(b).out))} · ${esc(root.DanzigEnterprisePolicy.LABELS[b.management.mode])}</small></span><span>${n(b.cash)} тал.<small>${s.workers(b.id).length} работников · ${Math.max(0,s.hiringSlots(b)-s.workers(b.id).length)} вакансий</small></span></summary><div class="household-family-body"><p>${esc(b.management.reason)}</p><div class="ledger-columns"><section><h3>Прогноз владельца</h3>${f?`<dl><dt>Продажи за день, среднее</dt><dd>${n(f.sold)} ед.</dd><dt>Ожидаемые продажи</dt><dd>${n(f.expected)} ед./день</dd><dt>Предоплачено покупателями</dt><dd>${n(f.committed)} ед.</dd><dt>Расчётная себестоимость</dt><dd>${n(f.unitCost)} тал./ед.</dd><dt>Выручка после сбора</dt><dd>${n(f.unitNet)} тал./ед.</dd><dt>Маржа на единицу</dt><dd>${n(f.margin)} тал.</dd><dt>Желаемый оборотный запас</dt><dd>${n(f.reserve)} тал.</dd><dt>План оплаченной работы</dt><dd>${n(f.plannedHours)} ч.</dd></dl>`:'<p>Первая оценка — следующим утром.</p>'}</section><section><h3>Учёт за 7 дней</h3><dl><dt>Выручка после торговых сборов</dt><dd>${n(total('revenue'))} тал.</dd><dt>Стоимость проданных товаров</dt><dd>${n(total('cost'))} тал.</dd><dt>Прочие учтённые затраты</dt><dd>${n(total('overhead'))} тал.</dd><dt>Результат по проданному товару</dt><dd>${n(total('revenue')-total('cost')-total('overhead'))} тал.</dd><dt>Оплата труда</dt><dd>${n(total('wages'))} тал.</dd><dt>Поступившее сырьё</dt><dd>${n(total('inputs'))} тал.</dd></dl><p class="muted">Труд и сырьё входят в стоимость выпуска; повторно из результата не вычитаются. Непроданный товар остаётся на складе. Налог на прибыль, недвижимость и вложения смотрите отдельно в казне и договорах.</p></section></div><p><b>Возможный ассортимент:</b> ${s.productRecipes(b).map(r=>esc(s.goodName(r.out))).join(' · ')}</p>${b.product?`<p class="muted">${esc(b.product.reason)}</p>`:''}${b.ownerId?`<button data-ledger-person="${b.ownerId}">Владелец: ${esc(s.person(b.ownerId)?.name)}</button>`:''}</div></details>`;}).join('')}</div>
    <h3>Стройка: материалы и труд</h3><p class="muted">Дата в договоре — минимальный срок. Новые здания и улучшения ждут фактических поставок и работы. Начальный капитал мастерской хранится отдельно от доступной суммы подряда; остаток возвращается заказчику. Старые оплаченные подряды сохраняют прежние условия.</p>
    <div class="household-list">${sites.map(({b,p,q})=>`<details class="household-family construction-card"><summary><span><b>${esc(b.name)}</b><small>${esc(p.name||'Новое здание')} · ${esc(q.reason)}</small></span><span>${n(q.work/q.required*100)}% работы<small>Осталось ${n(q.cash-q.capital)} тал.</small></span></summary><div class="household-family-body"><div class="ledger-columns"><section><h3>Оплаченный подряд</h3><dl><dt>Внесено заказчиком</dt><dd>${n(q.budget)} тал.</dd><dt>Капитал будущей мастерской</dt><dd>${n(q.capital)} тал.</dd><dt>Материалы</dt><dd>${n(q.materialSpent)} тал.</dd><dt>Перевозка и работа</dt><dd>${n(q.wages)} тал.</dd><dt>Выполнено работы</dt><dd>${n(q.work/60)} / ${n(q.required/60)} ч.</dd></dl></section><section><h3>Материалы на площадке</h3><dl>${Object.entries(q.needs).map(([g,need])=>`<dt>${esc(s.goodName(g))}</dt><dd>${n(q.stock[g])} / ${n(need)}</dd>`).join('')}</dl></section></div></div></details>`).join('')||'<p>Активных местных подрядов нет. Решение о новом проекте принимают владельцы и ратуша.</p>'}</div>
    <h3>Разные товары — разные применения</h3><div class="ledger-table-wrap"><table><thead><tr><th>Ремесло</th><th>Обычный выпуск</th><th>Альтернатива</th><th>Зачем покупать</th></tr></thead><tbody><tr><td>Пекарня</td><td>Хлеб</td><td>Галеты</td><td>Чуть менее сытные; потери при хранении 0,2% в день против 2,5% у хлеба</td></tr><tr><td>Пильный двор</td><td>Доски</td><td>Балки</td><td>Каркас новых зданий и перестройка</td></tr><tr><td>Кузница</td><td>Инструменты</td><td>Гвозди</td><td>Местные строительные заказы</td></tr><tr><td>Гончар</td><td>Посуда</td><td>Черепица</td><td>Кровля домов и мастерских</td></tr></tbody></table></div><p class="muted">Потери при хранении с начала наблюдений: ${Object.entries(s.materialLife?.lost||{}).map(([g,v])=>esc(s.goodName(g))+' '+n(v)).join(' · ')||'ещё нет данных'}. Это порча запасов, не потребление и не продажа.</p>`;
  }
  root.DanzigEnterpriseView={render};
})(typeof window!=='undefined'?window:globalThis);
