(function(root){
  'use strict';
  const Names=typeof module!=='undefined'&&module.exports?require('./names.js'):root.DanzigNames;
  const W=typeof module!=='undefined'&&module.exports?require('./world.js'):root.DanzigWorld;
  const Housing=typeof module!=='undefined'&&module.exports?require('./housing.js'):root.DanzigHousing;
  const Construction=typeof module!=='undefined'&&module.exports?require('./construction.js'):root.DanzigConstruction;
  const R=typeof module!=='undefined'&&module.exports?require('./residences.js'):root.DanzigResidences;
  const specs={clay:{cost:240,days:2,cash:100},home:{cost:180,days:2,cash:0},farm:{cost:280,days:2,cash:100},pasture:{cost:280,days:2,cash:100},wood:{cost:240,days:2,cash:100},fish:{cost:280,days:2,cash:100},mill:{cost:380,days:3,cash:120},bakery:{cost:340,days:3,cash:120},tailor:{cost:320,days:3,cash:120},potter:{cost:300,days:3,cash:120},weaver:{cost:300,days:3,cash:120},carpenter:{cost:340,days:3,cash:120},sawmill:{cost:320,days:3,cash:120},smith:{cost:400,days:3,cash:140},charcoal:{cost:260,days:2,cash:100}};
  function options(s,lot){return lot.types.flatMap(type=>type==='home'?R.allowed(lot).map((residence,i)=>({value:i?'home:'+residence:'home',type,residence,...R.kinds[residence]})):[{value:type,type,name:s.buildingType(type),...specs[type]}]);}
  function ensure(s){s.expansion??={sinceDay:s.day,immigrants:0,nextFamilyDay:s.day,history:[]};return s.expansion;}
  function capacity(s){return Housing.capacity(s);}
  function build(s,id,type,guild=null){const lot=W.expansionLots.find(l=>l.id===id),choice=lot&&options(s,lot).find(o=>o.value===type),spec=choice;type=choice?.type||type;if(!lot||!lot.types.includes(type)||!spec)return {ok:false,message:'На этом участке нельзя построить выбранное здание'};if(s.building(id))return {ok:false,message:'Участок уже занят'};const fee=guild?spec.cost*s.guilds.permitRate/100:0;if((guild?guild.cash:s.treasury)<spec.cost+fee)return {ok:false,message:`Нужно ${spec.cost} талеров в казне`};
    const b=W.expansionBuilding(id,type);if(type==='home')b.residence=choice.residence;if(guild&&type==='home'&&!R.eligible(b,[s.person(guild.leaderId)]))return{ok:false,message:'Для поместья нужен дворянский владелец.'};b.name=(choice.name||s.buildingType(type))+' · '+lot.name;b.stock=Object.fromEntries(Object.keys(s.goods).map(g=>[g,0]));b.cash=0;b.construction={startedAt:s.now,until:s.now+spec.days*1440,cost:spec.cost,capital:spec.cash,permit:fee,guildId:guild?.id||null};if(guild){guild.cash-=spec.cost+fee;b.guildId=guild.id;b.ownerId=guild.leaderId;b.name=s.buildingType(type)+' · '+guild.name;s.changeTreasury(fee,'guildPermit');s.guilds.permitsPaid+=fee;}else{s.changeTreasury(-spec.cost,'construction');s.spendDevelopmentFund?.(spec.cost);}s.buildings.push(b);Construction.start(s,b,b.construction,[{type:guild?'guild':'city',id:guild?.id??null,amount:spec.cost}],spec.cash);s.initializeDevelopment?.();ensure(s).history.unshift({id,type,day:s.day,cost:spec.cost});s.log(`Начато строительство: ${b.name}. Подряд ${spec.cost} тал., срок от ${spec.days} дн. Материалы и труд оплачиваются внутри города; открытие ждёт реального завершения.`,'economy',null,{title:'Город расширяется',buildingId:id});return {ok:true,message:'Строительство началось. По завершении появятся жильё или вакансии.',buildingId:id};
  }
  function tick(s){for(const b of s.buildings.filter(b=>b.construction&&b.construction.until<=s.now)){const local=!!b.construction.local;if(!Construction.finish(s,b,b.construction))continue;if(!local)b.cash=b.construction.capital??specs[b.type].cash;const r=s.productionRecipe(b);if(r&&!local){for(const[g,n]of Object.entries(r.inputs))b.stock[g]=n*4;b.stock.tools=b.type==='smith'?0:2;}if(b.type==='home'&&!local)b.stock.bread=6;delete b.construction;s.openedEnterprise?.(b);Housing.review(s);for(const p of s.alive)s.observe(p,b);s.assignJobs();s.log(`Открыт ${b.name}. ${b.type==='home'?'Город получил '+R.spec(b).name.toLowerCase()+' на '+Housing.room(b)+' человек без тесноты.':'Мастерская ищет работников и поставщиков.'}`,'economy',null,{title:'Строительство завершено',buildingId:b.id});}}
  function settlement(s){const e=ensure(s);if(s.day<e.nextFamilyDay)return {ok:false,message:`Следующая семья сможет прибыть с дня ${e.nextFamilyDay+1}`};if(s.incidents.some(e=>e.type==='blockade'&&e.status==='active'))return {ok:false,message:'Блокада закрыла въезд переселенцам'};const home=Housing.newcomerHome(s);if(!home)return {ok:false,message:'Нет подходящего дома для семьи: после заселения допускается не более 167% комфортной вместимости (10 человек в доме на 6). Постройте или расширьте жильё.'};const jobs=s.buildings.reduce((n,b)=>n+(s.isOpen(b)?Math.max(0,s.jobSlots(b)-s.workers(b.id).length):0),0);if(jobs<2)return {ok:false,message:'Для переселенцев нужны хотя бы две свободные вакансии'};
    const surname=Names.family(s),a=s.createPerson(Names.name(s,'m'),surname,'m',28,home.id),b=s.createPerson(Names.name(s,'f'),surname,'f',25,home.id),c=s.createPerson(Names.name(s,'f',b),surname,'f',5,home.id);a.spouseId=b.id;b.spouseId=a.id;c.parents=[a.id,b.id];b.lastBirth=s.day;for(const p of [a,b,c]){s.initializeMind(p);p.bag.bread=3;Object.assign(p,{x:W.nodes.southRoad.x,y:W.nodes.southRoad.y,navNode:'southRoad',location:null,goal:home.id,path:W.route('southRoad','b:'+home.id),arriving:true,action:'Переселяется',reason:'Идёт с дороги в новый дом'});}s.assignJobs();if(!s.person(s.mayorId)?.alive)s.election();Housing.review(s);e.immigrants+=3;e.nextFamilyDay=s.day+6;s.log(`По южной дороге прибывает семья: двое взрослых и ребёнок. Их дом — ${home.name}. С собой привезены сбережения и 9 порций хлеба.`,'family',a.id,{title:'Новые горожане',buildingId:home.id});return {ok:true,message:'Семья идёт в город по южной дороге. Следующее приглашение — через 6 дней.'};
  }
  function load(s){ensure(s);if(!Number.isFinite(s.expansion.nextFamilyDay)||!Number.isFinite(s.expansion.immigrants)||s.expansion.immigrants<0||!Array.isArray(s.expansion.history))throw Error('Некорректное расширение города');for(const b of s.buildings.filter(b=>b.expansion)){if(!W.expansionLots.some(l=>l.id===b.id&&l.types.includes(b.type))||b.construction&&(!Number.isFinite(b.construction.until)||b.construction.until<0))throw Error('Некорректный строительный проект');}}
  const api={specs,options,ensure,capacity,build,tick,settlement,load};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.DanzigExpansion=api;
})(typeof window!=='undefined'?window:globalThis);
