(function(root){
  'use strict';
  const node=typeof module!=='undefined'&&module.exports,Property=node?require('./property-tax.js'):root.DanzigPropertyTax,Budget=node?require('./city-budget.js'):root.DanzigCityBudget;
  const TAXES={income:{name:'Налог на заработок',max:30},sales:{name:'Сбор с торговой выручки',max:20},export:{name:'Экспортная пошлина',max:30}};
  const sum=o=>Object.values(o||{}).reduce((a,b)=>a+b,0),round=n=>Math.round(n*100)/100;
  function ensure(s){
    s.fiscal??={sinceDay:s.day,autoMayor:true,nextReview:s.day+1,taxes:{income:{enabled:s.tax>0,rate:s.tax||12},sales:{enabled:true,rate:5},export:{enabled:true,rate:10}},tithe:{enabled:true,rate:10,cityShare:30},days:[],history:[],lastReview:null};
    s.fiscal.infrastructure??={sinceDay:s.day,lastDay:s.day,due:0,paid:0,condition:100,arrears:0};s.fiscal.infrastructure.procurement??={sinceDay:s.day,localSpent:0,goods:{},days:[]};Property.ensure(s);Budget.ensure(s);return s.fiscal;
  }
  function record(s,key,amount){if(!amount)return;const f=ensure(s);let row=f.days.find(d=>d.day===s.day);if(!row){row={day:s.day};f.days.push(row);f.days=f.days.slice(-60);}row[key]=(row[key]||0)+amount;}
  function rate(s,key){const t=ensure(s).taxes[key];return t.enabled?t.rate:0;}
  function splitWage(s,gross,p){const f=ensure(s),taxable=p?Math.max(0,gross-Math.max(0,12-p.coins)):gross,tax=taxable*rate(s,'income')/100,tithe=(gross-tax)*(f.tithe.enabled?f.tithe.rate:0)/100,city=tithe*f.tithe.cityShare/100;return{gross,tax,tithe,city,church:tithe-city,net:gross-tax-tithe};}
  // The employer debits gross once. These transfers partition that same payment.
  function wage(s,p,gross,employer){Budget.recordWage(s,employer,gross);const split=splitWage(s,gross,p);p.coins+=split.net;p.earnedToday+=split.net;s.changeTreasury(split.tax,'tax');s.changeTreasury(split.city,'tithe');s.building('church').cash+=split.church;for(const[k,v]of Object.entries({grossWages:gross,wageTax:split.tax,wageRelief:gross*rate(s,'income')/100-split.tax,tithe:split.tithe,titheCity:split.city,titheChurch:split.church}))record(s,k,v);p.fiscalToday??={day:s.day,gross:0,tax:0,tithe:0,net:0};if(p.fiscalToday.day!==s.day)p.fiscalToday={day:s.day,gross:0,tax:0,tithe:0,net:0};for(const k of ['gross','tax','tithe','net'])p.fiscalToday[k]+=split[k];return split;}
  function sale(s,seller,gross,external=false){const key=external?'export':'sales',tax=gross*rate(s,key)/100;seller.cash+=gross-tax;if(seller.enterprise){seller.enterprise.revenue+=gross;seller.enterprise.totalRevenue+=gross;}s.changeTreasury(tax,external?'trade':'sales');record(s,external?'exportBase':'salesBase',gross);record(s,external?'exportTax':'salesTax',tax);return tax;}
  function announce(s,kind,text,automatic=false){const f=ensure(s),mayor=s.governmentOfficer?.('treasurer')||s.person(s.mayorId),author=automatic?(mayor?.name||'Бургомистр'):'Правительство';f.history.unshift({day:s.day,minute:s.minute,kind,author,text});f.history=f.history.slice(0,40);s.log(author+': '+text,'politics',automatic?mayor?.id:null,{title:kind==='tithe'?'Указ о церковной десятине':kind==='autonomy'?'Полномочия бургомистра':'Налоговый указ',importance:'major',buildingId:kind==='tithe'?'church':'hall'});}
  function describe(taxes){return Object.entries(TAXES).map(([key,spec])=>spec.name.toLowerCase()+': '+(taxes[key].enabled?taxes[key].rate+'%':'отменён')).join('; ');}
  function configureTaxes(s,data){const next={};for(const[k,spec]of Object.entries(TAXES)){const value=Number(data[k+'Rate']);if(!Number.isFinite(value)||value<0||value>spec.max)return{ok:false,message:`${spec.name}: ставка должна быть от 0 до ${spec.max}%`};next[k]={enabled:data[k+'Enabled']===true&&value>0,rate:value};}const f=ensure(s);f.taxes=next;f.autoMayor=false;f.property.auto=false;if(s.government)s.government.manual.treasurer=true;s.tax=rate(s,'income');announce(s,'taxes',describe(next)+'. Ручное управление: бургомистр не меняет ставки.');return{ok:true,message:'Налоги утверждены. Автоматический пересмотр отключён.'};}
  function configureTithe(s,data){const value=Number(data.rate),share=Number(data.cityShare);if(!Number.isFinite(value)||value<0||value>30||!Number.isFinite(share)||share<0||share>100)return{ok:false,message:'Десятина: 0–30%, доля города: 0–100%'};const f=ensure(s);f.tithe={enabled:data.enabled===true&&value>0,rate:value,cityShare:share};announce(s,'tithe',f.tithe.enabled?`Десятина ${value}% с заработка после городского налога; ${share}% сбора — в казну, ${100-share}% — церкви.`:'Церковная десятина отменена.');return{ok:true,message:'Условия десятины изменены для будущих выплат.'};}
  function setAuto(s,enabled){const f=ensure(s);f.autoMayor=!!enabled;f.property.auto=!!enabled;f.property.nextReview=s.day+1;if(s.government)s.government.manual.treasurer=!enabled;f.nextReview=s.day+1;announce(s,'autonomy',enabled?'Бургомистр самостоятельно пересматривает городские налоги каждые три дня. Условия десятины остаются у правительства.':'Ставки налогов зафиксированы; бургомистр больше их не меняет.');return{ok:true,message:enabled?'Первая оценка бюджета — следующим утром.':'Включено ручное управление налогами.'};}
  function budget(s){const f=ensure(s),start=Math.max(s.day-6,s.accounts.sinceDay),days=Math.max(0,s.day-start),rows=s.accounts.days.filter(d=>d.day>=start&&d.day<s.day),income={},expenses={};for(const r of rows){for(const[k,v]of Object.entries(r.income))income[k]=(income[k]||0)+v;for(const[k,v]of Object.entries(r.expenses))expenses[k]=(expenses[k]||0)+v;}const divisor=Math.max(1,days),regular=sum(income)-(income.custom||0),spending=sum(expenses)-(expenses.region||0)-(expenses.custom||0)-(expenses.construction||0)-(expenses.development||0)-(expenses.infrastructure||0),dailyDue=s.regionBill()/s.region.period,net=(regular-spending)/divisor-dailyDue-sum(upkeep(s)),operatingExpenses=Object.fromEntries(Object.entries(expenses).filter(([k])=>!['custom','construction','development','region','infrastructure'].includes(k)));operatingExpenses.food=Math.max(0,(expenses.food||0)-(income.marketRepayment||0));operatingExpenses.infrastructure=sum(upkeep(s))*divisor;operatingExpenses.region=dailyDue*divisor;return{days,income,expenses,operatingExpenses,net,observed:sum(income)-sum(expenses),dailyDue,reserve:Math.max(100,s.regionBill()*2+s.region.debt),church:sum(f.days.filter(d=>d.day>=start&&d.day<s.day).map(d=>d.titheChurch||0))};}
  function daily(s){const f=ensure(s);Property.review(s,budget(s));Property.daily(s);if(!f.autoMayor||s.day<f.nextReview)return;f.nextReview=s.day+3;const mayor=s.governmentOfficer?.('treasurer')||s.person(s.mayorId);if(!mayor?.alive||mayor.absence)return;const b=budget(s),before=describe(f.taxes);let reason='';
    if(s.region.debt>0||s.treasury<b.reserve||b.days>=3&&b.net<0&&s.treasury<b.reserve+Math.abs(b.net)*6){
      const hardship=s.alive.filter(p=>p.hunger<25||p.age>=16&&p.coins<2).length>Math.max(3,s.alive.length*.25);for(const[k,step]of [['income',2],['sales',2],['export',3]]){const t=f.taxes[k],cap=k==='income'?(hardship?12:18):k==='sales'?10:25;t.rate=Math.min(cap,Math.max(0,(t.enabled?t.rate:0)+step));t.enabled=t.rate>0;}if(hardship)reason='Льгота на заработок пополняет личный запас до 12 талеров; остальные заработки участвуют в сборах. '; 
      reason+=`Казна ${round(s.treasury)} тал., долг региону ${round(s.region.debt)} тал. — усиливаю сборы для покрытия расходов.`;
    }else if(b.days>=3&&b.net>5&&s.treasury>b.reserve*4){
      const key=['income','sales','export'].find(k=>f.taxes[k].enabled&&f.taxes[k].rate>0);if(key){const t=f.taxes[key];t.rate=Math.max(0,t.rate-2);t.enabled=t.rate>0;reason='Запас казны достаточен, текущие поступления покрывают расходы — снижаю нагрузку.';}
    }
    if(before===describe(f.taxes)&&reason)reason='Ставки уже достигли допустимого предела. Ограничиваю расходы, сохраняю льготы бедным.';s.tax=rate(s,'income');f.lastReview={day:s.day,net:round(b.net),reason:reason||'Сохраняю ставки: оснований для изменения пока нет.'};
    if(before!==describe(f.taxes))announce(s,'taxes',reason+' '+describe(f.taxes)+'.',true);
    s.recordGovernment?.('treasurer',mayor,f.lastReview.reason+' '+describe(f.taxes)+'.');
  }
  function churchRelief(s){const church=s.building('church');if(!s.commerce.outside.importEnabled||s.incidents.some(e=>e.type==='blockade'&&e.status==='active')||church.stock.bread>=10)return 0;const portions=Math.min(20,Math.floor(Math.max(0,church.cash-20)/.75));if(!portions)return 0;const cost=portions*.75;church.cash-=cost;church.stock.bread+=portions;record(s,'churchFood',cost);s.log(`Церковь купила ${portions} порций хлеба для бедных за ${cost.toFixed(1)} тал. из собственных средств.`,'economy',null,{title:'Церковная помощь',buildingId:'church'});return cost;}
  function load(s){const f=ensure(s),finite=(n,max)=>Number.isFinite(n)&&n>=0&&n<=max;if(typeof f.autoMayor!=='boolean'||!finite(f.sinceDay,1e9)||!finite(f.nextReview,1e9)||!Array.isArray(f.days)||!Array.isArray(f.history)||!Object.entries(TAXES).every(([k,v])=>typeof f.taxes?.[k]?.enabled==='boolean'&&finite(f.taxes[k].rate,v.max))||typeof f.tithe?.enabled!=='boolean'||!finite(f.tithe.rate,30)||!finite(f.tithe.cityShare,100))throw Error('Некорректная налоговая политика');const v=f.infrastructure;if(!['sinceDay','lastDay','due','paid','arrears'].every(k=>finite(v[k],1e12))||!finite(v.condition,100))throw Error('Некорректное содержание города');const q=v.procurement;if(!finite(q.sinceDay,1e12)||!finite(q.localSpent,1e12)||!q.goods||!Object.values(q.goods).every(n=>finite(n,1e12))||!Array.isArray(q.days)||!q.days.every(r=>finite(r.day,1e12)&&finite(r.localSpent,1e12)))throw Error('Некорректные закупки города');Property.load(s);Budget.load(s);s.tax=rate(s,'income');}
  function upkeep(s){const ready=s.buildings.filter(b=>!b.construction);return{roads:ready.length*.07+s.buildings.filter(b=>b.expansion&&!b.construction).length*.2,sanitation:s.alive.length*.045,watch:(2+s.living.length*.02)*(s.government?.guard||1),buildings:ready.reduce((n,b)=>n+((b.development?.level||1)-1)*.08,0),hall:Math.max(0,(s.building('hall').development?.level||1)-1)*.8*(1-(s.building('hall').development?.extras.length||0)*.1)};}
  // Maintenance is already debited by the budget. Local invoices reuse that payment.
  function localSupplies(s,paid){
    if(!paid)return;const q=ensure(s).infrastructure.procurement;let localSpent=0;
    for(const [good,share]of [['tools',.3],['planks',.25],['wood',.2],['cloth',.15],['pottery',.1]]){
      let remaining=paid*.7*share;
      const sellers=s.buildings.filter(b=>s.isOpen(b)&&s.productionRecipe(b)?.out===good).sort((a,b)=>s.price(a,good)-s.price(b,good)||a.cash-b.cash);
      for(const b of sellers){const reserved=s.commerce.orders.filter(o=>o.seller===b.id&&o.good===good).reduce((n,o)=>n+o.amount,0),price=s.price(b,good),amount=Math.min(Math.max(0,b.stock[good]-reserved),remaining/price);if(amount<=0)continue;
        const cost=amount*price;b.stock[good]=Math.max(0,b.stock[good]-amount);sale(s,b,cost);remaining=Math.max(0,remaining-cost);localSpent+=cost;q.goods[good]=(q.goods[good]||0)+amount;
      }
    }
    q.localSpent+=localSpent;q.days.push({day:s.day,localSpent});q.days=q.days.slice(-60);
  }
  function maintain(s){const v=ensure(s).infrastructure;if(v.lastDay===s.day)return;v.lastDay=s.day;const costs=upkeep(s),due=sum(costs),paid=Budget.spend(s,'infrastructure',due+Math.min(v.arrears,due*.25));localSupplies(s,paid);v.due=due;v.paid+=paid;v.arrears=Math.max(0,v.arrears+due-paid);v.condition=Math.max(20,Math.min(100,v.condition+(paid>=due?2:-3)));if(paid<due&&s.day%6===0)s.log('Ратуша отложила часть содержания дорог, стражи и уборки. Задолженность подрядчикам: '+round(v.arrears)+' тал.','economy',null,{title:'Содержание города',buildingId:'hall'});}
  function prepareBudget(s){return Budget.prepare(s,budget(s),sum(upkeep(s)));}
  const api={Property,Budget,prepareBudget,TAXES,ensure,rate,splitWage,wage,sale,configureTaxes,configureTithe,setAuto,budget,daily,churchRelief,upkeep,maintain,load};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.DanzigFinance=api;
})(typeof window!=='undefined'?window:globalThis);
