(function(root){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n=v=>Number(v||0).toLocaleString('ru-RU',{maximumFractionDigits:1});
  const name=(s,id)=>esc(s.person(id)?.name||'Пока не назначено');
  function render(s,p,learning=''){
    const m=p.mind,c=p.career,plan=p.plan,h=m?.forecast,v=m?.personality;
    if(!m)return'<p class="muted">Составляет первые планы.</p>';
    const progress=m.goal==='security'?Math.min(100,(h?.coins||0)/Math.max(1,h?.reserve||1)*100):m.goal==='mastery'?Math.min(100,p.skill/6*100):m.goal==='enterprise'?Math.min(100,p.coins/300*100):m.goal==='standing'?p.reputation:0;
    return `<div class="mind-goal"><span class="eyebrow">ИНТЕЛЛЕКТ 2.0 · ЛОКАЛЬНЫЕ РЕШЕНИЯ</span><h3>${esc(plan?.title||'Обдумывает следующий шаг')}</h3><p>${esc(p.reason)}</p>${plan?.estimatedMinutes?`<small>Оценка полного плана: ${n(plan.estimatedMinutes)} мин.</small>`:''}</div>
      <ol class="plan-steps">${plan?plan.steps.map((x,i)=>`<li class="${i<plan.index?'done':i===plan.index?'current':'pending'}"><span>${i<plan.index?'✓':i+1}</span><div>${esc(x.label)}<small>${esc(s.building(x.target)?.name)}${i===plan.index&&p.path.length?' · в пути':''}</small></div></li>`).join(''):'<li class="pending">Выбирает подходящую задачу…</li>'}</ol>
      ${p.cargo?`<p class="cargo-note">Груз: ${n(p.cargo.amount)} ед. ${esc(s.goodName(p.cargo.good))} → ${esc(s.building(p.cargo.to)?.name)}</p>`:''}
      <section class="mind-section"><div class="section-label">ЧТО ПЕРЕВЕСИЛО <span>ПРИОРИТЕТ</span></div>${(p.considered||[]).slice(0,3).map((x,i)=>`<div class="mind-option ${i===0?'chosen':''}"><div><strong>${esc(x.title)}</strong><b>${n(x.score)}</b></div><p>${esc(x.reason)}</p>${x.factors?.length?`<small>${x.factors.map(esc).join(' · ')}</small>`:''}</div>`).join('')||'<p class="muted">Решение появится с первым ходом времени.</p>'}
      ${m.lastReplan?`<p class="mind-replan">Последний пересмотр: ${esc(m.lastReplan)}</p>`:''}</section>
      <section class="mind-section"><div class="section-label">ЦЕЛЬ НА БУДУЩЕЕ</div><strong>${esc(root.DanzigMind.GOALS[m.goal]||p.ambition)}</strong>${m.goal!=='home'?`<div class="mind-meter" role="meter" aria-label="Прогресс жизненной цели" aria-valuenow="${Math.round(progress)}" aria-valuemin="0" aria-valuemax="100"><i style="width:${progress}%"></i></div>`:''}<small class="muted">${m.goal==='security'?`${n(h?.coins)} / ${n(h?.reserve)} тал. семейного резерва`:m.goal==='mastery'?`Мастерство ${n(p.skill)} / 6`:m.goal==='enterprise'?'Ориентир: 300 тал. личного капитала; разрешение и прочие условия проверяются отдельно':m.goal==='standing'?`Репутация ${n(p.reputation)} / 100`:'Теснота повышает приоритет переезда и улучшений'}</small></section>
      <section class="mind-section"><div class="section-label">СЕМЕЙНЫЙ ПЛАН</div>${h?`<dl class="mind-facts"><dt>Запас в доме</dt><dd>${n(h.foodDays)} дня</dd><dt>Еда на сутки</dt><dd>≈ ${n(h.dailyFood)} порц.</dd><dt>Закупки</dt><dd>${name(s,h.shopper)}</dd><dt>Уход за больным</dt><dd>${h.carer?name(s,h.carer):'Сейчас не требуется'}</dd></dl><p class="muted">${m.claims.some(x=>x.duty==='provision'&&x.until>s.now)?'Уже взял закупку на себя. Другие учитывают обещанные припасы.':'Личные кошельки раздельны; еда в доме общая.'}</p>`:'Составляет прогноз.'}</section>
      <section class="mind-section"><div class="section-label">ХАРАКТЕР <span>${m.inheritedFrom.length?'СЕМЕЙНЫЕ ЧЕРТЫ':'ЛИЧНЫЕ ЧЕРТЫ'}</span></div><div class="mind-traits">${Object.entries(root.DanzigMind.LABELS).map(([k,label])=>`<div><span>${label}</span><meter min="0" max="100" value="${Math.round(v[k]*100)}" aria-label="${label}"></meter><b>${Math.round(v[k]*100)}</b></div>`).join('')}</div></section>
      <section class="mind-section"><div class="section-label">ТРУД И ОПЫТ</div><p>${esc(s.building(p.jobId)?.name||p.role)}${c?.apprentice?` · ученик, ${n(c.training)} / 480 мин. практики · 70% ставки`:''}</p><small class="muted">Собеседований: ${c?.applications||0} · трудоустройств: ${c?.changes||0} · известных объявлений: ${c?.known?.filter(x=>x.slots>0&&s.now-x.at<4320).length||0}</small>
      ${m.contexts.slice(0,4).map(x=>`<div class="memory-item"><span>${esc(s.building(x.subject)?.name||x.subject)}: ${esc(x.why)}</span><small>${x.source==='personal'?'Личный опыт':'Со слов '+name(s,x.source)} · уверенность ${Math.round(x.confidence*Math.exp(-Math.max(0,s.now-x.at)/10080)*100)}%</small></div>`).join('')}
      ${m.search?`<p class="muted">Последний поиск плана: ${m.search.expanded} из ${m.search.limit} допустимых состояний, шагов ${m.search.depth}.</p>`:''}</section>
      <div class="section-label">ЛИЧНАЯ ПАМЯТЬ</div>${p.memories.slice(0,3).map(x=>`<div class="memory-item"><span>${esc(x.text)}</span><small>День ${Math.floor(x.at/1440)+1}</small></div>`).join('')}${root.DanzigSocietyView.person(s,p)}${learning}`;
  }
  function dashboard(s,card){
    const adults=s.alive.filter(p=>p.age>=16&&p.age<65&&!p.absence),searching=adults.filter(p=>!p.jobId),apprentices=adults.filter(p=>p.career?.apprentice),changes=s.people.reduce((n,p)=>n+(p.career?.changes||0),0);
    return`<div class="ledger-kpis">${card('Трудоспособных',adults.length)}${card('Без работы',searching.length,'Ищут объявления и проходят собеседование')}${card('Учеников в мастерских',apprentices.length)}${card('Трудоустройств',changes,'С начала учёта ИИ 2.0')}</div><p class="ledger-notice">Решения принимаются локально: нужды, характер, семейный прогноз, доступные сведения и опыт. Неудача у одного работодателя не означает отказ от труда вообще. Нажмите на имя, чтобы увидеть планы и причины выбора.</p><div class="ledger-table-wrap"><table><thead><tr><th>Житель</th><th>Работа</th><th>Жизненная цель</th><th>Сейчас</th><th>Принят / заявок</th></tr></thead><tbody>${adults.map(p=>`<tr><td><button data-ledger-person="${p.id}">${esc(p.name)}</button></td><td>${esc(s.building(p.jobId)?.name||'Ищет работу')}${p.career?.apprentice?' · ученик':''}</td><td>${esc(root.DanzigMind.GOALS[p.mind?.goal]||p.ambition)}</td><td>${esc(p.plan?.title||p.action)}</td><td>${p.career?.changes||0} / ${p.career?.applications||0}</td></tr>`).join('')}</tbody></table></div>`;
  }
  root.DanzigMindView={render,dashboard};
})(typeof window!=='undefined'?window:globalThis);
