(function(root){
 'use strict';
 const node=typeof module!=='undefined'&&module.exports,W=node?require('./world.js'):root.DanzigWorld,H=node?require('./households.js'):root.DanzigHouseholds,S=node?require('./social-life.js'):root.DanzigSocial;
 const publicTypes=new Set(['hall','clinic','school','dock','market','market2']),round=n=>Math.round(n*100)/100,live=p=>p?.alive&&!p.absence,here=(p,target)=>live(p)&&p.location===target&&!p.path.length;
 function ensure(s){s.properties??={version:1,sinceDay:s.day,lastDay:s.day,nextListing:1,nextOffer:1,nextLease:1,records:{},listings:[],offers:[],leases:[],escrow:0,history:[],totals:{sales:0,volume:0,rent:0,maintenance:0,depositsReturned:0}};register(s);return s.properties;}
 function entry(s,b){return s.properties?.records[b?.id];}
 function owner(s,b){const r=entry(s,b);return r?.holder==='person'?s.person(r.holderId):r?.holder==='guild'?s.person(s.guilds.groups.find(g=>g.id===r.holderId)?.leaderId):null;}
 function wallet(s,r){return r.holder==='person'?{object:s.person(r.holderId),key:'coins'}:r.holder==='guild'?{object:s.guilds.groups.find(g=>g.id===r.holderId),key:'cash'}:r.holder==='church'?{object:s.building('church'),key:'cash'}:{object:s,key:'treasury'};}
 function credit(s,r,amount,category='propertyRent'){if(!amount)return;const w=wallet(s,r);if(!w.object)return;if(w.object===s)s.changeTreasury(amount,category);else{w.object[w.key]+=amount;if(r.holder==='person')s.recordHouseholdIncome?.(w.object,amount);}}
 function register(s){
  const v=s.properties;if(!v)return;
  for(const lot of W.expansionLots)if(!v.records[lot.id])v.records[lot.id]={id:lot.id,holder:'city',holderId:null,shares:[{holder:'city',id:null,part:1}],since:s.day,land:true,registeredBuilding:false,let:true,lastReview:-6,maintenancePaid:0,maintenanceMissed:0};
  for(const b of s.buildings){let r=v.records[b.id];if(r?.registeredBuilding)continue;const citizen=s.person(b.ownerId)||(!b.expansion&&b.type==='home'?s.living.filter(p=>p.age>=18&&p.homeId===b.id).sort((a,b)=>a.id-b.id)[0]:null),g=s.guilds.groups.find(g=>g.id===b.guildId),holder=g?'guild':b.type==='church'?'church':publicTypes.has(b.type)||!citizen?'city':'person',holderId=g?.id??(holder==='person'?citizen.id:null);r=v.records[b.id]={id:b.id,holder,holderId,shares:[{holder,id:holderId,part:1}],since:s.day,land:false,registeredBuilding:true,let:true,lastReview:-6,maintenancePaid:0,maintenanceMissed:0};if(b.type==='home')b.ownerId=owner(s,b)?.id||null;}
 }
 function appraisal(s,b){if(!b)return 0;const base=b.type==='home'?({cottage:180,townhouse:420,manor:1800}[b.residence]||180):360,level=b.development?.level||1,extras=b.development?.extras?.length||0;return round(base*(1+(level-1)*1.4+extras*.15)*(b.damaged?.65:1));}
 function rate(s,b,use='home'){return round(use==='workshop'?Math.max(.5,appraisal(s,b)*.002):Math.max(.15,appraisal(s,b)*.0012));}
 function note(s,b,text){const v=s.properties;v.history.unshift({at:s.now,buildingId:b.id,text});v.history=v.history.slice(0,100);s.log(text,'economy',owner(s,b)?.id||null,{title:'Собственность и аренда',buildingId:b.id});}
 function sameFamily(s,p,b){const o=owner(s,b);return o&&(o.id===p.id||H.family(s,p).some(q=>q.id===o.id));}
 function tenantWallet(s,l){return l.use==='workshop'?{object:s.building(l.buildingId),key:'cash',reserve:20}:{object:s.person(l.tenantId),key:'coins',reserve:12};}
 function activeLease(s,p,b,use='home'){return s.properties.leases.find(l=>l.status==='active'&&l.buildingId===b.id&&l.use===use&&(l.tenantId===p.id||use==='home'&&H.family(s,p).some(q=>q.id===l.tenantId)));}
 function canLease(s,p,b,use='home',legacy=false,group=null){ensure(s);const r=entry(s,b);if(!r||!live(p)||p.age<16||b.construction||!r.let||b.type==='home'&&use!=='home'||b.type!=='home'&&use!=='workshop'||use==='workshop'&&!s.productionRecipe(b))return false;if(use==='home'&&p.homeId!==b.id&&s.living.filter(q=>q.homeId===b.id).length+(group||H.family(s,p)).filter(q=>q.homeId!==b.id).length>Math.floor(s.buildingCapacity(b)*5/3))return false;if(use==='home'&&sameFamily(s,p,b))return true;if(activeLease(s,p,b,use))return true;const w=use==='home'?p.coins:b.cash;return legacy||w>=(use==='home'?12:20)+rate(s,b,use)*2;}
 function lease(s,p,b,use='home',{legacy=false,group=null}={}){
  if(!canLease(s,p,b,use,legacy,group))return{ok:false,message:'Арендодатель не предлагает помещение или не хватает средств на залог.'};if(use==='home'&&sameFamily(s,p,b))return{ok:true};let l=activeLease(s,p,b,use);if(l)return{ok:true,lease:l};
  const v=ensure(s),r=entry(s,b),daily=rate(s,b,use),deposit=legacy?0:daily*2,from=use==='home'?{object:p,key:'coins'}:{object:b,key:'cash'};from.object[from.key]-=deposit;v.escrow+=deposit;l={id:v.nextLease++,buildingId:b.id,tenantId:p.id,use,landlord:r.holder,landlordId:r.holderId,status:'active',started:s.day,until:s.day+24,lastDay:s.day,rate:daily,deposit,arrears:0,paid:0,legacy};v.leases.push(l);H.invalidate(s);note(s,b,p.name+' заключил договор: '+(use==='home'?'жильё':'мастерская')+', '+daily.toFixed(2)+' тал./день, залог '+deposit.toFixed(2)+', срок 24 дня.');return{ok:true,lease:l};
 }
 function housingAccess(s,p,group,b,commit=false){if(!s.properties)return true;if(!canLease(s,p,b,'home',false,group))return false;return commit?lease(s,p,b,'home',{group}).ok:true;}
 function expense(s,p){const v=s.properties;if(!v)return 0;const ids=new Set(H.family(s,p).map(q=>q.id));return v.leases.filter(l=>l.status==='active'&&l.use==='home'&&ids.has(l.tenantId)).reduce((n,l)=>n+l.rate,0);}
 function closeLease(s,l){if(l.status!=='active')return;const v=s.properties,r=entry(s,s.building(l.buildingId)),settlement=Math.min(l.deposit,l.arrears);v.escrow-=l.deposit;credit(s,r,settlement);l.arrears-=settlement;l.paid+=settlement;v.totals.rent+=settlement;const refund=l.deposit-settlement,w=tenantWallet(s,l);if(w.key==='coins'&&!w.object?.alive){const heir=w.object&&successor(s,w.object);if(heir)heir.coins+=refund;else s.changeTreasury(refund,'estateTransfer');}else if(w.object)w.object[w.key]+=refund;else s.changeTreasury(refund,'estateTransfer');v.totals.depositsReturned+=refund;l.deposit=0;l.status='ended';note(s,s.building(l.buildingId),'Договор №'+l.id+' завершён: залог возвращён за вычетом '+settlement.toFixed(2)+' тал. подтверждённой задолженности.');}
 function list(s,p,b,ask){const v=ensure(s),r=entry(s,b);if(!here(p,b.id)||p.age<18||owner(s,b)?.id!==p.id||r.holder!=='person'||r.shares.length!==1||b.construction||b.development?.project||!['home'].includes(b.type)&&!s.productionRecipe(b)||!Number.isFinite(ask)||ask<appraisal(s,b)*.5||ask>appraisal(s,b)*2)return{ok:false,message:'Владелец может лично выставить свободное от стройки право собственности на двор.'};let l=v.listings.find(l=>l.buildingId===b.id&&l.status==='open');if(l)return{ok:true,listing:l};l={id:v.nextListing++,buildingId:b.id,sellerId:p.id,ask:round(ask),listed:s.day,expires:s.day+18,status:'open',soldFor:null,buyerId:null};v.listings.unshift(l);v.listings=v.listings.filter(l=>l.status==='open').concat(v.listings.filter(l=>l.status!=='open').slice(0,60));note(s,b,p.name+' выставил двор за '+l.ask+' тал. Действующие права жильцов и оператора сохраняются.');return{ok:true,listing:l};}
 function propose(s,p,l,bid){const v=ensure(s);if(!l||l.status!=='open'||!here(p,'hall')||p.id===l.sellerId||p.age<18||!Number.isFinite(bid)||bid<l.ask*.75||bid>l.ask*1.1||p.coins<bid+60||v.offers.some(o=>o.status==='pending'&&o.buyerId===p.id))return{ok:false,message:'Предложение требует личного визита и свободного капитала.'};const o={id:v.nextOffer++,listingId:l.id,buyerId:p.id,bid:round(bid),at:s.now,until:s.now+3*1440,status:'pending',reason:'Ожидает встречи сторон в ратуше'};v.offers.unshift(o);v.offers=v.offers.filter(o=>o.status==='pending').concat(v.offers.filter(o=>o.status!=='pending').slice(0,60));return{ok:true,offer:o};}
 function transfer(s,r,b,buyer,price){const previous={holder:r.holder,id:r.holderId};r.holder='person';r.holderId=buyer.id;r.shares=[{holder:'person',id:buyer.id,part:1}];r.since=s.day;if(b.type==='home')b.ownerId=buyer.id;
  for(const l of s.properties.leases.filter(l=>l.buildingId===b.id&&l.status==='active')){l.landlord='person';l.landlordId=buyer.id;for(const c of s.court?.cases||[])if(c.kind==='rent'&&c.sourceId===l.id&&c.status!=='closed'){c.plaintiffId=buyer.id;c.reason='Право требования перешло приобретателю двора';c.judgeId=null;c.startedAt=null;}}
  if(s.productionRecipe(b)&&b.ownerId&&b.ownerId!==buyer.id&&!s.properties.leases.some(l=>l.status==='active'&&l.buildingId===b.id&&l.use==='workshop'))lease(s,s.person(b.ownerId),b,'workshop',{legacy:true});
  // Selling an occupied home creates no eviction and no retroactive bill.
  if(b.type==='home'){const seen=new Set();for(const p of s.living.filter(p=>p.homeId===b.id&&p.age>=18)){const family=H.family(s,p);if(family.some(q=>seen.has(q.id)))continue;family.forEach(q=>seen.add(q.id));if(!sameFamily(s,p,b))lease(s,p,b,'home',{legacy:true});}}
  note(s,b,'Переход права собственности: '+(previous.holder==='person'?s.person(previous.id)?.name:previous.holder)+' → '+buyer.name+'. Цена сделки '+price+' тал.; касса предприятия, товары, договоры и жильцы сохраняются.');H.invalidate(s);
 }
 function sign(s,p,o){const v=ensure(s),l=v.listings.find(l=>l.id===o?.listingId),b=s.building(l?.buildingId),r=entry(s,b),buyer=s.person(o?.buyerId),seller=s.person(l?.sellerId);if(!o||o.status!=='pending'||l?.status!=='open'||s.now>o.until||![buyer?.id,seller?.id].includes(p.id)||!here(buyer,'hall')||!here(seller,'hall')||r.holder!=='person'||r.holderId!==seller.id||b.construction||b.development?.project)return{ok:false,message:'Стороны, право собственности или условия сделки изменились.'};
  const min=l.ask*(seller.coins<60?.8:.92+(seller.mind.personality.thrift-.5)*.08);if(o.bid<min){o.status='declined';o.reason='Продавец считает предложенную цену недостаточной';return{ok:false,message:o.reason};}if(buyer.coins<o.bid+60){o.status='declined';o.reason='Покупатель не сохранил свободные деньги';return{ok:false,message:o.reason};}
  buyer.coins-=o.bid;seller.coins+=o.bid;o.status='accepted';o.reason='Договор подписан обеими сторонами, деньги переданы продавцу';l.status='sold';l.soldFor=o.bid;l.buyerId=buyer.id;transfer(s,r,b,buyer,o.bid);v.totals.sales++;v.totals.volume+=o.bid;for(const other of v.offers.filter(x=>x!==o&&x.listingId===l.id&&x.status==='pending')){other.status='declined';other.reason='Двор уже продан';}return{ok:true};
 }
 function successor(s,p){return s.living.filter(q=>q.id!==p.id&&(q.id===p.spouseId||q.spouseId===p.id||q.parents.includes(p.id)||p.parents.includes(q.id))).sort((a,b)=>Number(b.age>=18)-Number(a.age>=18)||Number(b.id===p.spouseId)-Number(a.id===p.spouseId)||b.age-a.age||a.id-b.id)[0];}
 function inheritance(s){if(!s.properties)return;for(const r of Object.values(s.properties.records)){if(r.holder!=='person'||s.person(r.holderId)?.alive)continue;const dead=s.person(r.holderId),heir=dead&&successor(s,dead),b=s.building(r.id);r.holder=heir?'person':'city';r.holderId=heir?.id||null;r.shares=[{holder:r.holder,id:r.holderId,part:1}];r.since=s.day;if(b?.type==='home')b.ownerId=heir?.id||null;for(const l of s.properties.leases.filter(l=>l.buildingId===r.id&&l.status==='active')){l.landlord=r.holder;l.landlordId=r.holderId;}if(b)note(s,b,'После смерти владельца двор передан '+(heir?heir.name:'городской опеке')+'. Обязательства и права пользования сохранены.');}
  for(const l of s.properties.leases.filter(l=>l.status==='active'&&!s.person(l.tenantId)?.alive)){const b=s.building(l.buildingId),dead=s.person(l.tenantId),heir=dead&&successor(s,dead);if(heir&&l.use==='home'&&heir.homeId===b.id)l.tenantId=heir.id;else if(l.use==='workshop'&&live(s.person(b.ownerId)))l.tenantId=b.ownerId;else closeLease(s,l);}
 }
 function daily(s){const v=ensure(s);inheritance(s);if(v.lastDay>=s.day)return;v.lastDay=s.day;
  for(const b of s.buildings){if(b.construction)continue;const r=entry(s,b),operator=s.person(b.ownerId);if(s.productionRecipe(b)&&live(operator)&&owner(s,b)?.id!==operator.id&&!activeLease(s,operator,b,'workshop'))lease(s,operator,b,'workshop');if(b.type==='home'){const seen=new Set();for(const p of s.living.filter(p=>p.homeId===b.id&&p.age>=18&&!p.arriving&&!p.absence)){const family=H.family(s,p);if(family.some(q=>seen.has(q.id)))continue;family.forEach(q=>seen.add(q.id));if(!sameFamily(s,p,b)&&!activeLease(s,p,b))lease(s,p,b,'home',{legacy:p.coins<12+rate(s,b)*2});}}}
  for(const l of v.listings)if(l.status==='open'&&(s.day>l.expires||entry(s,s.building(l.buildingId))?.holderId!==l.sellerId||!s.person(l.sellerId)?.alive))l.status='withdrawn';for(const o of v.offers)if(o.status==='pending'&&(s.now>o.until||!s.person(o.buyerId)?.alive)){o.status='expired';o.reason='Встреча не состоялась в срок';}
  for(const l of v.leases.filter(l=>l.status==='active')){const p=s.person(l.tenantId),b=s.building(l.buildingId),r=entry(s,b);if(!p?.alive||l.use==='home'&&(p.homeId!==b.id||sameFamily(s,p,b))||l.use==='workshop'&&(b.ownerId!==p.id||owner(s,b)?.id===p.id)){closeLease(s,l);continue;}if(l.lastDay>=s.day)continue;l.lastDay=s.day;if(l.until<=s.day)l.until=s.day+24;const due=b.damaged||b.construction?0:l.rate,w=tenantWallet(s,l),paid=Math.min(due,Math.max(0,w.object[w.key]-w.reserve));w.object[w.key]-=paid;credit(s,r,paid);l.paid+=paid;l.arrears+=due-paid;v.totals.rent+=paid;if(l.use==='home'&&paid)s.recordHousingExpense?.(p,paid,'rent');}
  const repairer=s.buildings.find(b=>b.type==='carpenter'&&s.isOpen(b)&&s.workers(b.id).length);for(const b of s.buildings){const r=entry(s,b);if(!r||!['person','guild'].includes(r.holder)||b.construction||!repairer)continue;const w=wallet(s,r),due=round(appraisal(s,b)*.0006),paid=Math.min(due,Math.max(0,w.object[w.key]-60));w.object[w.key]-=paid;s.payPropertyMaintenance(repairer,paid);if(r.holder==='person'&&paid)s.recordHousingExpense?.(w.object,paid,'propertyMaintenance');r.maintenancePaid+=paid;r.maintenanceMissed+=due-paid;v.totals.maintenance+=paid;}
  v.leases=v.leases.filter(l=>l.status==='active'||l.arrears>0).concat(v.leases.filter(l=>l.status==='ended'&&l.arrears<=0).slice(-80));H.invalidate(s);
 }
 function candidates(s,p,add,step){if(!live(p)||p.age<18||p.hunger<25||p.energy<22||s.hour<8||s.hour>=18)return;const v=ensure(s),pending=v.offers.find(o=>o.status==='pending'&&s.now<=o.until&&(o.buyerId===p.id||v.listings.find(l=>l.id===o.listingId)?.sellerId===p.id));if(pending){add('propertySign','Заключить сделку с недвижимостью',83,'Вторая сторона приглашена в ратушу; деньги перейдут только при согласии обоих',[step('propertySign','hall','Обсудить и подписать договор',{duration:45,offerId:pending.id})]);return;}
  const owned=s.buildings.filter(b=>entry(s,b)?.holder==='person'&&entry(s,b).holderId===p.id&&!b.construction&&!b.development?.project);
  const surplus=owned.find(b=>b.id!==p.homeId&&b.id!==p.jobId&&(b.type==='home'||s.productionRecipe(b))&&!v.listings.some(l=>l.status==='open'&&l.buildingId===b.id)&&s.day-entry(s,b).lastReview>=6);if(surplus&&(p.coins<120||owned.length>2))add('propertyList','Выставить лишний двор на продажу',49,'Содержание лишней собственности требует средств',[step('propertyList',surplus.id,'Оценить двор и объявить цену',{duration:35,buildingId:surplus.id,ask:appraisal(s,surplus)*(p.coins<60?.9:1.08)})]);
  if(p.coins>240&&s.day-(p.lastPropertyOfferDay??-6)>=6){const l=v.listings.filter(l=>l.status==='open'&&l.sellerId!==p.id&&p.coins>=l.ask+80&&(!s.productionRecipe(s.building(l.buildingId))||p.mind.personality.ambition>.6)).sort((a,b)=>Number(b.buildingId===p.homeId)-Number(a.buildingId===p.homeId)||a.ask-b.ask)[0];if(l)add('propertyOffer','Предложить покупку двора',46+p.mind.personality.ambition*12,'Хочу владеть жильём или получать аренду; сохраняю личный резерв',[step('propertyOffer','hall','Предложить цену продавцу',{duration:25,listingId:l.id,bid:l.ask*.95})]);}
 }
 function execute(s,p,step){if(step.kind==='propertyList'){const b=s.building(step.buildingId),r=list(s,p,b,step.ask);entry(s,b).lastReview=s.day;return r;}if(step.kind==='propertyOffer'){p.lastPropertyOfferDay=s.day;return propose(s,p,ensure(s).listings.find(l=>l.id===step.listingId),step.bid);}const o=ensure(s).offers.find(o=>o.id===step.offerId);if(o?.status==='accepted')return{ok:true};const l=ensure(s).listings.find(l=>l.id===o?.listingId);if(o?.status==='pending'&&s.now<=o.until&&(!here(s.person(o.buyerId),'hall')||!here(s.person(l?.sellerId),'hall')))return{ok:false,pending:true};return sign(s,p,o);}
 function load(s){const existing=!!s.properties,v=ensure(s),num=x=>Number.isFinite(x)&&x>=0,id=x=>Number.isInteger(x)&&x>0,holder=(h,id)=>h==='person'?!!s.person(id):h==='guild'?s.guilds.groups.some(g=>g.id===id):['city','church'].includes(h)&&id===null;if(v.version!==1||!['sinceDay','lastDay','escrow'].every(k=>num(v[k]))||v.lastDay>s.day||!['nextListing','nextOffer','nextLease'].every(k=>id(v[k]))||!Array.isArray(v.history)||v.history.length>100||!Array.isArray(v.listings)||v.listings.length>200||!Array.isArray(v.offers)||v.offers.length>300||!Array.isArray(v.leases)||v.leases.length>500||!Object.values(v.totals).every(num))throw Error('Некорректный реестр недвижимости');
  for(const [key,r]of Object.entries(v.records))if(key!==r.id||!s.building(key)&&!W.expansionLots.some(l=>l.id===key)||!holder(r.holder,r.holderId)||!Array.isArray(r.shares)||r.shares.length!==1||r.shares[0].holder!==r.holder||r.shares[0].id!==r.holderId||r.shares[0].part!==1||!['since','maintenancePaid','maintenanceMissed'].every(k=>num(r[k])))throw Error('Некорректное право собственности');
  for(const [rows,next,kind]of [[v.listings,v.nextListing,'listing'],[v.offers,v.nextOffer,'offer'],[v.leases,v.nextLease,'lease']]){const ids=new Set();for(const row of rows){if(!id(row.id)||row.id>=next||ids.has(row.id))throw Error('Повторный номер имущественного договора');ids.add(row.id);if(kind==='listing'&&(!s.building(row.buildingId)||!s.person(row.sellerId)||!num(row.ask)||!['open','sold','withdrawn'].includes(row.status)))throw Error('Некорректное объявление');if(kind==='offer'&&(!s.person(row.buyerId)||!num(row.bid)||!num(row.until)||!['pending','accepted','declined','expired'].includes(row.status)))throw Error('Некорректное предложение');if(kind==='lease'&&(!s.person(row.tenantId)||!s.building(row.buildingId)||!holder(row.landlord,row.landlordId)||!['home','workshop'].includes(row.use)||!['active','ended'].includes(row.status)||!['rate','deposit','arrears','paid','started','until','lastDay'].every(k=>num(row[k]))))throw Error('Некорректная аренда');}}
  if(Math.abs(v.escrow-v.leases.reduce((n,l)=>n+l.deposit,0))>1e-6)throw Error('Несогласованный залоговый счёт');if(!existing)for(const b of s.buildings)if(b.type==='home'&&owner(s,b))b.ownerId=owner(s,b).id;
 }
 const api={ensure,entry,owner,wallet,register,appraisal,rate,sameFamily,activeLease,canLease,lease,housingAccess,expense,closeLease,list,propose,transfer,sign,inheritance,daily,candidates,execute,load};if(node)module.exports=api;else root.DanzigProperty=api;
})(typeof window!=='undefined'?window:globalThis);
