(function(root){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=n=>Number(n||0).toLocaleString('ru-RU',{maximumFractionDigits:1});
  const total=o=>Object.values(o||{}).reduce((n,v)=>n+v,0),day=at=>'День '+(Math.floor(at/1440)+1);
  const categories={property:'Сбор с дворов и участков',development:'Развитие общественных зданий',administration:'Содержание магистрата',marketRepayment:'Возврат лавкой стоимости снабжения',infrastructure:'Дороги, уборка и стража',guildProfit:'Налог с прибыли мастерских',guildPermit:'Разрешения на стройку',construction:'Строительство и дороги',tax:'Налог с заработка',trade:'Экспортные пошлины',sales:'Сбор с продаж',cityExport:'Городской экспорт',tithe:'Доля десятины',region:'Сборы региону',food:'Продовольствие',services:'Общественные службы',repair:'Ремонт',festival:'Праздники',custom:'Ваши события'};
  const goods={grain:'Зерно',flour:'Мука',bread:'Хлеб',fish:'Рыба',wood:'Древесина',tools:'Инструменты',wool:'Шерсть',cloth:'Ткань',clothes:'Одежда',planks:'Доски',furniture:'Мебель',coal:'Уголь',iron:'Железо',clay:'Глина',pottery:'Посуда'};
  const eventNames={guild:'Гильдии',crisis:'Кризисы',military:'Военная служба',fire:'Пожары',family:'Семейная жизнь',politics:'Совет города',custom:'Ваши события',death:'Утраты',food:'Продовольствие',tribute:'Регион',health:'Здоровье',economy:'Хозяйство',life:'Повседневность',career:'Ремёсла',friendship:'Знакомства',conflict:'Ссоры',festival:'Праздники',weather:'Погода',experiment:'Перемены',reaction:'Реакции',season:'Сезоны'};
  const card=(label,value,note='')=>`<article class="report-kpi"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></article>`;
  const empty=text=>`<p class="report-empty">${esc(text)}</p>`;
  function bars(values,names={},limit=10){const entries=Object.entries(values).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,limit),max=Math.max(1,...entries.map(([,v])=>v));return entries.length?`<div class="report-bars">${entries.map(([k,v])=>`<div><span>${esc(names[k]||k)}</span><b>${num(v)}</b><i style="--bar:${v/max*100}%"></i></div>`).join('')}</div>`:empty('Пока нет записей.');}
  function chart(r,key='total'){const labels={total:'Живые жители',treasury:'Городская казна, талеры',happiness:'Благополучие, %'},points=r.timeline;if(points.length<2||points[0].at===points.at(-1).at)return empty('Время ещё не прошло: для графика нужны наблюдения в разные моменты.');const lo=Math.min(0,...points.map(p=>p[key])),hi=Math.max(1,...points.map(p=>p[key])),first=points[0].at,last=points.at(-1).at;
    const coords=points.map(p=>[54+(p.at-first)/(last-first)*814,24+(hi-p[key])/(hi-lo)*156]);const path=coords.map((p,i)=>(i?'L':'M')+p.map(n=>n.toFixed(1)).join(',')).join(' ');
    return `<svg class="report-chart" viewBox="0 0 920 218" role="img" aria-label="${esc(labels[key])}: ${num(points[0][key])} → ${num(points.at(-1)[key])}"><title>${esc(labels[key])}</title>${[0,.5,1].map(f=>`<path class="chart-grid" d="M54 ${24+156*f}H868"/><text x="44" y="${28+156*f}" text-anchor="end">${num(hi-(hi-lo)*f)}</text>`).join('')}<path class="chart-area" d="${path} L868,180 L54,180 Z"/><path class="chart-line" d="${path}"/><circle cx="${coords.at(-1)[0]}" cy="${coords.at(-1)[1]}" r="4"/><text x="54" y="207">${day(first)}</text><text x="868" y="207" text-anchor="end">${day(last)}</text></svg>`;
  }
  function hero(r){return `<header class="report-hero"><div class="report-seal" aria-hidden="true">D</div><div><span class="report-overline">ЛЕТОПИСЬ ВОЛЬНОГО ГОРОДА</span><h1>Город, который<br>прожил свою историю.</h1><p>Данциг · ${r.year===1450?'1450':'1450–'+r.year} · ${num(r.elapsedDays)} игровых дней</p></div><div class="report-era"><strong>${num(r.elapsedYears)}</strong><span>городских лет</span><small>24 дня в одном году</small></div></header>`;}
  function overview(r,metric,exporting){const p=r.population,peak=r.peaks.total,stories=[];
    if(r.dynasties[0])stories.push(`<strong>Род ${esc(r.dynasties[0].name)}</strong> оставил самый многочисленный след: ${r.dynasties[0].total} жителей с этой фамилией за историю.`);
    if(r.lineage.length>1)stories.push(`Сохранилась цепочка родства длиной <strong>${r.lineage.length} поколений</strong> — ${esc(r.lineage[0].name)} → ${esc(r.lineage.at(-1).name)}.`);
    if(r.city.moves)stories.push(`Семьи <strong>${r.city.moves} раз</strong> выбрали переезд из тесного дома.`);
    if(!p.living)stories.push('Последний житель ушёл. В этой летописи остались люди, ремёсла и решения города.');
    else if(!stories.length)stories.push('Это только начало истории. Поколения, семейные связи и городские рекорды появятся по мере жизни города.');
    return `<div class="report-kpis">${card('Живых жителей',num(p.living),`${p.ever} человек в истории`)}${card('Родилось в городе',num(p.births),`${p.deaths} умерло · ${p.immigrants} прибыло`)}${card('Поколений',num(r.learning.generations),`${num(r.learning.lessons)} семейных уроков`)}${card('Казна на финале',num(r.economy.treasury)+' тал.',`Долг региону: ${num(r.economy.debt)}`)}</div>
      <section class="report-paper"><div class="report-section-heading"><div><span class="report-overline">РИТМ ГОРОДА</span><h2>Как менялась жизнь</h2></div>${exporting?'':`<div class="report-chart-switch" aria-label="Показатель графика">${[['total','Население'],['treasury','Казна'],['happiness','Благополучие']].map(([key,label])=>`<button data-report-metric="${key}" aria-pressed="${key===metric}">${label}</button>`).join('')}</div>`}</div>${chart(r,metric)}<p class="report-caption">Наблюдения с игрового дня ${Math.floor(r.coverage.chartSince/1440)+1}. На длинных историях график разрежается; рекорды наблюдений сохраняются отдельно.</p></section>
      <div class="report-columns"><section class="report-paper"><span class="report-overline">ТО, ЧТО ЗАПОМНИТСЯ</span><h2>След в истории</h2><div class="report-insights">${stories.map(t=>`<p>${t}</p>`).join('')}</div></section><section class="report-paper report-records"><span class="report-overline">ГОРОДСКИЕ РЕКОРДЫ</span><h2>Лучшие мгновения</h2>${[['Больше всего жителей',peak,'чел.'],['Самая полная казна',r.peaks.treasury,'тал.'],['Наивысшее благополучие',r.peaks.happiness,'%']].map(([label,v,unit])=>`<div><span>${label}<small>${v?day(v.at):'Нет наблюдений'}</small></span><b>${num(v?.value)} <em>${unit}</em></b></div>`).join('')}</section></div>
      <div class="report-kpis report-secondary">${card('Построено дворов',num(r.city.built),`${r.city.constructing} ещё строится`)}${card('Семейных переездов',num(r.city.moves),`${r.city.crowded} домов остаются тесными`)}${card('Перевезено грузов',num(r.economy.deliveries),'По городским дорогам')}${card('На службе',num(p.away),'Живут, но временно вне города')}</div>`;
  }
  function population(r){const heroes=[['Долгая жизнь',r.heroes.oldest,p=>`${p.age} лет · ${p.alive?'жив на финале':'возраст на момент смерти'}`],['Большая семья',r.heroes.parent,p=>`${p.children} известных детей`],['Опыт поколений',r.heroes.experienced,p=>`${num(p.successes)} завершённых планов`]];
    return `<div class="report-people-awards">${heroes.map(([title,p,note])=>`<article><span class="report-overline">${title}</span><h3>${p?esc(p.name):'—'}</h3><p>${p?esc(note(p)):'Жителей пока нет'}</p><small>${p?'Поколение '+p.generation:''}</small></article>`).join('')}</div>
      <section class="report-paper"><span class="report-overline">ОТ РОДИТЕЛЕЙ К ДЕТЯМ</span><h2>Одна из самых длинных линий родства</h2><div class="report-lineage">${r.lineage.map(p=>`<article><small>Поколение ${p.generation}</small><strong>${esc(p.name)}</strong><span>${p.age} лет · ${p.alive?'жив':'ушёл из жизни'}</span></article>`).join('')||empty('Родственные связи ещё не появились.')}</div><p class="report-caption">Каждый следующий человек — ребёнок предыдущего. Фамилии могут меняться.</p></section>
      <section class="report-paper"><span class="report-overline">ЛЮДИ И ОБУЧЕНИЕ</span><h2>Что оставило каждое поколение</h2><div class="report-table-wrap"><table><thead><tr><th>Поколение</th><th>Всего / живы</th><th>Планы: успех</th><th>Средний навык</th><th>Уроки семьи</th><th>Унаследовано целей</th><th>Сильнейшая оценка цели</th></tr></thead><tbody>${r.generations.map(g=>`<tr><th>${g.generation}</th><td>${g.total} / ${g.living}</td><td>${g.successRate===null?'Нет опыта':num(g.successRate)+'%'}<small>${num(g.successes)} / ${num(g.successes+g.failures)} попыток</small></td><td>${num(g.skill)}</td><td>${num(g.lessons)}</td><td>${num(g.inherited)}</td><td>${esc(g.favorite?.title||'Опыт ещё не накоплен')}<small>${g.favorite?'Средняя оценка: '+num(g.favorite.value):''}</small></td></tr>`).join('')}</tbody></table></div><p class="report-caption">Успех — выполнение плана, а не оценка качества жизни. Старшие поколения имели больше времени для обучения; врождённые и усвоенные предпочтения могут быть неудачными.</p></section>
      <div class="report-columns"><section class="report-paper"><h2>Имена, пережившие эпоху</h2>${r.dynasties.map((f,i)=>`<div class="report-dynasty"><b>${String(i+1).padStart(2,'0')}</b><div><strong>${esc(f.name)}</strong><span>${f.generations} покол. · ${f.living} живы на финале</span></div><em>${f.total}</em></div>`).join('')}<p class="report-caption">Рейтинг по фамилии, включая умерших. Это не доказательство родства каждого однофамильца.</p></section><section class="report-paper"><h2>Рождения и утраты</h2><div class="report-kpis">${card('Новых жизней',num(r.population.births))}${card('Ушедших',num(r.population.deaths))}</div>${bars(r.population.causes,{oldAge:'Старость',hunger:'Голод',illness:'Болезнь',other:'Иные причины',unknown:'Причина не сохранена'})}</section></div>`;
  }
  function economy(r){const e=r.economy;return `<div class="report-kpis">${card('Доходы казны',num(total(e.income))+' тал.','За доступный период учёта')}${card('Расходы казны',num(total(e.expenses))+' тал.','За тот же период')}${card('Выплачено региону',num(e.paidRegion)+' тал.',`Учёт с дня ${e.regionSince+1}`)}${card('Городской экспорт',num(e.exportRevenue)+' тал.',`Выручка с дня ${e.exportSince+1}`)}</div>
      <p class="report-note">Доходы и расходы учтены с дня ${r.coverage.moneySince+1}. Начальная казна не является доходом. Экспорт и платежи региону показаны также отдельно и могут охватывать более длинный период — складывать эти карточки не нужно.</p>
      <div class="report-columns"><section class="report-paper"><span class="report-overline">ОТКУДА ПРИХОДИЛИ ДЕНЬГИ</span><h2>Доходы города</h2>${bars(e.income,categories)}${r.development?`<h3>Развитие города</h3><p>Ратуша ${r.development.hallLevel} уровня · дворов выше I уровня: ${r.development.upgraded}. Завершено улучшений: ${r.development.completed}; вложено владельцами ${num(r.development.spent)} тал.</p>`:''}${r.guilds?`<h3>Гильдии на финале</h3><p>Частных проектов: ${r.guilds.built}</p>${r.guilds.groups.map(g=>`<p>${esc(g.name)}: ${g.assets} предприятий, ${num(g.cash)} тал. капитала, ${num(g.dividends)} тал. выплат участникам.</p>`).join('')}`:''}</section><section class="report-paper"><span class="report-overline">НА ЧТО ЖИЛ ГОРОД</span><h2>Расходы и обязательства</h2>${bars(e.expenses,categories)}</section></div>
      <div class="report-columns"><section class="report-paper"><span class="report-overline">РУКАМИ ГОРОЖАН</span><h2>Главные ремёсла</h2>${bars(e.production,goods,15)}<p class="report-caption">Произведённые единицы товаров с дня ${r.coverage.statisticsSince+1}. Сырьё и готовая продукция показаны раздельно, их стоимость здесь не сравнивается.</p></section><section class="report-paper"><h2>Хлеб насущный</h2>${bars(e.consumption,goods)}<p class="report-caption">Съедено с дня ${r.coverage.statisticsSince+1}.</p><div class="report-records"><div><span>Еда на финале</span><b>${num(e.food)} <em>порций</em></b></div><div><span>Завершено маршрутов</span><b>${num(e.trips)}</b></div><div><span>Комфортных мест</span><b>${r.city.comfortable}</b></div></div></section></div>`;}
  function history(r){return `<div class="report-columns"><section class="report-paper"><span class="report-overline">ГОЛОСА ГОРОДА</span><h2>Из чего сложилась история</h2>${bars(r.counts,eventNames,12)}<p class="report-caption">Количество записей по темам, а не уникальных происшествий. Для старого города сохранена доступная часть хроники с дня ${r.coverage.eventSince+1}, после обновления счётчики накапливаются постоянно.</p></section><section class="report-paper"><h2>На пороге следующей главы</h2>${r.activeCrises.length?`<ul class="report-open-events">${r.activeCrises.map(e=>`<li>${esc(e.title)}<small>Оставалось активным на момент завершения</small></li>`).join('')}</ul>`:empty('Все вызванные временные события завершились.')}<p class="report-caption">Завершение симуляции не разрешает кризисы автоматически.</p>${r.mayor?`<p>Последний бургомистр — <strong>${esc(r.mayor.name)}</strong>.</p>`:''}</section></div>
      <section class="report-paper"><span class="report-overline">ПАМЯТНЫЕ СТРАНИЦЫ</span><h2>Хроника этой эпохи</h2><p class="report-caption">Выборка важных записей: первые и недавние события каждой темы, с приоритетом критических.</p><div class="report-timeline">${r.stories.map(e=>`<article class="${e.importance==='critical'?'critical':''}"><time>День ${e.day+1}<small>${Math.floor(e.minute/60).toString().padStart(2,'0')}:${(e.minute%60).toString().padStart(2,'0')}</small></time><div><span class="report-overline">${esc(e.label||eventNames[e.type]||e.type)}</span><h3>${esc(e.title||e.label||'Городская история')}</h3><p>${esc(e.text)}</p>${e.effects?.length?`<small>${esc(e.effects.join(' · '))}</small>`:''}</div></article>`).join('')||empty('Больших событий ещё не случилось. Город только проснулся.')}</div></section>`;}
  const sections={overview,population,economy,history},tabs=[['overview','Облик эпохи'],['population','Люди и поколения'],['economy','Казна и ремёсла'],['history','События и наследие']];
  const coverage=r=>r.coverage.legacy?`Архив подключён: день ${Math.floor(r.coverage.installedAt/1440)+1}. Родство и жители взяты из сохранённой истории; графики, деньги и события — из доступных журналов и новых наблюдений. Утраченные сведения не восстановлены.`:'Архив ведётся с основания города. Графики показывают периодические наблюдения, хроника — выборку памятных событий.';
  function body(r,section='overview',metric='total',exporting=false){return `${hero(r)}<div class="report-content">${exporting?tabs.map(([id,title])=>`<section class="report-export-section"><h2 class="report-chapter">${title}</h2>${sections[id](r,metric,true)}</section>`).join(''):sections[section](r,metric,false)}<footer class="report-coverage"><span class="report-overline">ОБ ЭТОЙ ЛЕТОПИСИ</span><p>${coverage(r)}</p><p>Итоговый срез · день ${r.day+1} · ${String(Math.floor(r.at%1440/60)).padStart(2,'0')}:${String(Math.floor(r.at%60)).padStart(2,'0')}. Все значения относятся к этому моменту.</p></footer></div>`;}
  function exportHTML(r,css){return `<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Данциг — летопись, день ${r.day+1}</title><style>${css}</style><body class="report-export"><main>${body(r,'overview','total',true)}</main></body></html>`;}
  class ReportView{
    constructor(getSim,changed){this.getSim=getSim;this.changed=changed;this.root=document.getElementById('report-dialog');this.section='overview';this.metric='total';this.root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.reportTab){this.section=b.dataset.reportTab;this.render();}if(b.dataset.reportMetric){this.metric=b.dataset.reportMetric;this.render();}if(b.hasAttribute('data-report-close'))this.root.close();if(b.hasAttribute('data-report-resume')){this.getSim().resume();this.root.close();this.changed();}if(b.hasAttribute('data-report-download'))this.download();});}
    open(){if(!this.getSim().conclusion)return;this.section='overview';this.render();this.root.showModal();}
    render(){const r=this.getSim().conclusion;this.root.innerHTML=`<div class="report-toolbar"><span>ИСТОРИЯ ЗАВЕРШЕНА</span><div><button data-report-download>Скачать HTML</button><button data-report-resume>Продолжить историю</button><button data-report-close aria-label="Закрыть итоговый отчёт">×</button></div></div><nav class="report-tabs" aria-label="Разделы итогового отчёта">${tabs.map(([id,title])=>`<button data-report-tab="${id}" aria-pressed="${this.section===id}">${title}</button>`).join('')}</nav><div class="report-scroll">${body(r,this.section,this.metric)}</div><span class="report-download-status" role="status"></span>`;}
    download(){try{const css=[...document.styleSheets].filter(s=>s.href?.endsWith('/report.css')).flatMap(s=>[...s.cssRules].map(r=>r.cssText)).join('\n');const blob=new Blob([exportHTML(this.getSim().conclusion,css)],{type:'text/html;charset=utf-8'});if(this.exportURL)URL.revokeObjectURL(this.exportURL);this.exportURL=URL.createObjectURL(blob);const a=document.createElement('a');a.href=this.exportURL;a.download='danzig-chronicle-day-'+(this.getSim().conclusion.day+1)+'.html';document.body.append(a);a.click();a.remove();const status=this.root.querySelector('[role=status]');status.textContent='Отчёт подготовлен. ';const link=document.createElement('a');link.href=this.exportURL;link.target='_blank';link.rel='noopener';link.textContent='Открыть готовый HTML';status.append(link);}catch{this.root.querySelector('[role=status]').textContent='Не удалось подготовить файл. Отчёт остаётся доступен здесь.';}}
  }
  if(typeof module!=='undefined'&&module.exports)module.exports={body,chart,exportHTML};else root.DanzigReportView=ReportView;
})(typeof window!=='undefined'?window:globalThis);
