(function(root){
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n=x=>Number(x||0).toLocaleString('ru-RU',{maximumFractionDigits:1});
  const personName=(s,id)=>s.person(id)?.name||'Нет участника';
  const parties=(s,a)=>a.kind==='supply'?`${s.building(a.sellerId)?.name} → ${s.building(a.buyerId)?.name}`:`${personName(s,a.lenderId)} → ${a.kind==='venture'?s.building(a.buildingId)?.name:personName(s,a.borrowerId)}`;
  function person(s,p){
    const i=p.intention,book=s.agreements,relationships=Object.entries(p.relationships).map(([id,value])=>({q:s.person(id),value})).filter(x=>x.q?.alive&&Math.abs(x.value)>=10).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value)).slice(0,4);
    const deals=(book?.items||[]).filter(a=>(a.borrowerId===p.id||a.lenderId===p.id)&&root.DanzigAgreements.live(a)).slice(-4);
    return`<section class="mind-section"><div class="section-label">ДЛИТЕЛЬНОЕ НАМЕРЕНИЕ</div>${i?`<strong>${esc(root.DanzigMind.GOALS[i.goal])}</strong><p>${esc(root.DanzigIntentions.TACTICS[i.goal][i.tactic])}</p><small class="muted">С дня ${i.since+1} · следующий пересмотр с дня ${i.reviewAt+1} · ориентир выполнен на ${Math.round(i.progress*100)}%${i.paused?' · временно занят насущными нуждами':''}</small>${i.history.slice(0,2).map(x=>`<p class="mind-replan">День ${x.day+1}: ${esc(x.reason)}</p>`).join('')}`:'Пока формируется.'}</section>
      <section class="mind-section"><div class="section-label">ЛЮДИ, КОТОРЫЕ ВЛИЯЮТ НА ЖИЗНЬ</div>${relationships.map(({q,value})=>`<div class="society-link"><button data-person="${q.id}">${esc(q.name)}</button><span>${value>=0?'Доверие':'Конфликт'} ${n(Math.abs(value))}</span></div>`).join('')||'<p class="muted">Значимых личных связей пока нет. Родство отдельно учитывается при просьбах о помощи.</p>'}</section>
      <section class="mind-section"><div class="section-label">ОБЕЩАНИЯ И ДОГОВОРЫ</div>${deals.map(a=>`<div class="mind-option"><strong>${esc(root.DanzigAgreements.LABELS[a.kind])} · ${esc(root.DanzigAgreements.STATUS[a.status])}</strong><p>${esc(parties(s,a))}</p><small>${a.status==='proposed'?`Обсуждают ${n(a.requested)} тал.`:`Передано ${n(a.amount)}, возвращено ${n(a.paid)} тал.`} · срок: день ${a.due+1}</small></div>`).join('')||'<p class="muted">Незавершённых денежных договорённостей нет.</p>'}
      ${p.career?.termUntil>s.day?`<p class="muted">Трудовое соглашение: не менее ${n(p.career.contractRate)} тал./ч. до дня ${p.career.termUntil+1}. Выплата зависит от фактической работы и кассы двора.</p>`:''}</section>`;
  }
  function render(s,card){
    const book=s.agreements,active=book.items.filter(root.DanzigAgreements.live),overdue=active.filter(a=>a.status==='overdue'),relations=s.alive.reduce((v,p)=>v+Object.values(p.relationships).filter(x=>x>=25).length,0);
    return`<div class="ledger-kpis">${card('Действующих договорённостей',active.length)}${card('Просрочено',overdue.length)}${card('Передано на займы и вклады',n(book.transferred)+' тал.','Из реальных кошельков жителей')}${card('Направленных связей доверия',relations,'Отношение каждого к каждому считается отдельно')}</div>
      <p class="ledger-notice">Заём требует личной встречи и согласия кредитора. Партнёрский вклад получает долю свободной прибыли и может принести убыток. Просроченная поставка сохраняет право на товар или возврат из кассы продавца. Государство не создаёт деньги для исполнения обещаний.</p>
      <h3>Договорённости и их последствия</h3><div class="ledger-table-wrap"><table><thead><tr><th>Стороны</th><th>Условия</th><th>Состояние</th><th>Передано / возвращено</th><th>Срок</th></tr></thead><tbody>${book.items.slice().sort((a,b)=>Number(root.DanzigAgreements.live(b))-Number(root.DanzigAgreements.live(a))||b.id-a.id).slice(0,45).map(a=>`<tr><td>${esc(parties(s,a))}</td><td>${esc(root.DanzigAgreements.LABELS[a.kind])}${a.kind==='venture'?' · 20% свободной прибыли':a.kind==='loan'?a.interest?' · 3% за весь срок':' · без процентов':` · ${n(a.units)} ед. ${esc(s.goodName(a.good))}`}</td><td><span class="deal-state ${a.status==='overdue'?'late':''}">${esc(root.DanzigAgreements.STATUS[a.status])}</span></td><td>${a.status==='proposed'?n(a.requested)+' обсуждается':n(a.amount)+' / '+n(a.kind==='supply'?a.refunded:a.paid)}${a.kind==='supply'?` · доставлено ${n(a.delivered)} ед.`:''}</td><td>День ${a.due+1}</td></tr>`).join('')||'<tr><td colspan="5">Договорённости появятся по мере встреч, просьб о помощи и заказов сырья.</td></tr>'}</tbody></table></div>
      <h3>Как хозяева управляют дворами</h3><div class="ledger-table-wrap"><table><thead><tr><th>Двор и хозяин</th><th>Решение</th><th>Причина</th><th>Ставка / цена</th></tr></thead><tbody>${s.buildings.filter(b=>b.management&&!b.construction).map(b=>`<tr><td>${esc(b.name)}<br><small>${esc(personName(s,b.ownerId))}</small></td><td>${esc(root.DanzigEnterprisePolicy.LABELS[b.management.mode])}</td><td>${esc(b.management.reason)}</td><td>${n(b.wage)} тал./ч. · ${Math.round((b.enterprise?.priceFactor||1)*100)}% городской цены</td></tr>`).join('')}</tbody></table></div>
      <h3>Истории договорённостей</h3>${book.history.slice(0,12).map(x=>`<p class="ledger-notice"><small>День ${x.day+1}</small> · ${esc(x.text)}</p>`).join('')||'<p class="muted">У каждой исполненной или нарушенной договорённости появится своя запись.</p>'}`;
  }
  root.DanzigSocietyView={person,render};
})(typeof window!=='undefined'?window:globalThis);
