// Historical scenario: obsolete tax UI and machine-specific dependencies.
// Excluded from tools/check.cjs. Use /?demo=1 with the browser tool instead.
const { chromium } = require('C:/Users/alale/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1150 }, deviceScaleFactor: 1 });
  const errors = [];
  const externalRequests = [];
  page.on('pageerror', e => errors.push(e.message));
  // This machine's antivirus injects its own browser script. It is outside the
  // application; leave it running and only audit requests made by this app.
  page.on('request', r => {
    if (!/^https?:/.test(r.url())) return;
    const hostname = new URL(r.url()).hostname;
    if (hostname === 'gc.kis.v2.scr.kaspersky-labs.com') return;
    if (hostname !== '127.0.0.1') externalRequests.push(hostname);
  });
  await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' });
  await page.evaluate(() => window.danzig.pause());
  await page.locator('#map[data-art=ready]').waitFor();
  assert.ok(await page.locator('.summary-heading').isVisible());
  await page.screenshot({ path: path.join(__dirname, '../preview-desktop.png'), fullPage: true });
  assert.equal(await page.locator('#population').innerText(), '48');
  const before = await page.evaluate(() => window.danzig.sim.minute);
  await page.waitForTimeout(400);
  assert.equal(await page.evaluate(() => window.danzig.sim.minute), before);
  await page.locator('[data-speed="3"]').click();
  assert.equal(await page.evaluate(() => window.danzig.speed), 3);
  await page.waitForTimeout(250);
  assert.ok(await page.evaluate(() => window.danzig.sim.minute) > before);
  await page.evaluate(() => window.danzig.pause());
  const map = await page.locator('#map').boundingBox();
  const point = await page.evaluate(() => { const b=danzig.sim.building('church');return danzig.map.screenPoint(b.x,b.y); });
  await page.mouse.click(map.x+point.x, map.y+point.y);
  assert.match(await page.locator('.building-detail h2').innerText(), /Церковь/);
  await page.locator('[data-tab="people"]').click();
  await page.locator('#people-search').fill('Анна');
  assert.ok(await page.locator('.people-list .person-row').count() >= 1);
  await page.locator('.people-list .person-row').first().click();
  assert.match(await page.locator('.person-heading h2').innerText(), /Анна/);
  assert.ok(await page.locator('.mind-goal').isVisible());
  await page.locator('[data-person-view="life"]').click();
  assert.ok(await page.locator('.need').count() >= 4);
  await page.locator('[data-person-view="mind"]').click();
  await page.locator('[data-tab="buildings"]').click();
  await page.locator('.building-row[data-building="mill"]').click();
  assert.match(await page.locator('.building-detail h2').innerText(), /мельница/i);
  await page.locator('[data-action="disrupt"]').click();
  assert.equal(await page.evaluate(() => danzig.sim.building('mill').closedUntil>danzig.sim.now),true);
  await page.locator('[data-tab="city"]').click();
  const food = await page.evaluate(() => window.danzig.sim.food);
  await page.locator('[data-action="food"]').click();
  assert.equal(await page.evaluate(() => window.danzig.sim.food), food + 75);
  await page.locator('#tax').fill('22');
  await page.locator('#tax').dispatchEvent('change');
  assert.equal(await page.evaluate(() => window.danzig.sim.tax), 22);
  await page.locator('[data-action="festival"]').click();
  assert.equal(await page.locator('[data-action="festival"]').isDisabled(), true);
  await page.locator('#next-day').click();
  assert.equal(await page.evaluate(() => window.danzig.sim.day), 1);
  assert.equal(await page.evaluate(() => window.danzig.sim.minute), 360);
  await page.locator('#save').click();
  await page.reload({ waitUntil: 'networkidle' });
  await page.evaluate(() => window.danzig.pause());
  assert.equal(await page.evaluate(() => window.danzig.sim.day), 1);
  assert.equal(await page.evaluate(() => window.danzig.sim.tax), 22);
  await page.locator('#help').click();
  assert.equal(await page.locator('#help-dialog').evaluate(e => e.open), true);
  await page.locator('#help-dialog .primary').click();
  await page.locator('#reset').click();
  await page.locator('#reset-dialog [data-close]').click();
  assert.equal(await page.evaluate(() => window.danzig.sim.day), 1);
  await page.locator('#reset').click();
  await page.locator('#confirm-reset').click();
  await page.evaluate(() => window.danzig.pause());
  assert.equal(await page.evaluate(() => window.danzig.sim.day), 0);
  await page.locator('[data-trigger=fire]').click();
  assert.ok(await page.locator('.reaction-box').innerText());
  assert.equal(await page.locator('[data-trigger=fire]').isDisabled(),true);
  await page.locator('[data-filter=important]').click();
  assert.equal(await page.locator('.news-card.minor').count(),0);
  await page.locator('#observe-event').click();
  assert.equal(await page.evaluate(() => danzig.paused),true);
  await page.evaluate(() => { window.danzig.advance(300);window.danzig.selectPerson(2); });
  await page.waitForTimeout(450);
  await page.locator('#toast').evaluate(e => e.hidden = true);
  await page.screenshot({ path: path.join(__dirname, '../preview-working-day.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(200);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: path.join(__dirname, '../preview-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 320, height: 750 });
  await page.waitForTimeout(150);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  assert.deepEqual(externalRequests, []);
  await page.goto('file:///'+path.join(__dirname,'../index.html').replaceAll('\\','/'));
  await page.waitForTimeout(300);
  assert.equal(await page.evaluate(() => danzig.sim.buildings.length),34);
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: map selection, pause, speed, plans, daily life, buildings, disruption, actions, tax, next day, persistence, help, reset, 390/320 px, offline file launch, zero external application requests.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
