const test=require('node:test'),assert=require('node:assert/strict');
const {Simulation,Commerce,Finance}=require('../sim.js');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const copy=s=>Simulation.fromJSON(JSON.parse(JSON.stringify(s)));
test('объём внешнего спроса конечен, непроданное остаётся на складе',()=>{const s=new Simulation();s.commerce.stock.tools=10000;const before=s.treasury,price=Commerce.quote(s,'tools');Commerce.exportGoods(s);close(s.commerce.stock.tools,9992);assert.ok(s.treasury-before<8*price);assert.ok(Commerce.quote(s,'tools')<price);const cash=s.treasury;Commerce.exportGoods(s);close(s.treasury,cash);});
test('город и частные мастерские делят лимит, без повторного обнуления в тот же день',()=>{const s=new Simulation();s.commerce.stock.tools=7;Commerce.exportGoods(s);const deal=Commerce.sellOutside(s,'tools',100);close(deal.amount,1);close(Commerce.sellOutside(s,'tools',100).amount,0);const r=copy(s);close(Commerce.sellOutside(r,'tools',100).amount,0);});
test('разбивка экспорта на много сделок не обходит падение цены',()=>{const a=new Simulation(),b=new Simulation();const one=Commerce.sellOutside(a,'wood',40);let value=0;for(let i=0;i<40;i++)value+=Commerce.sellOutside(b,'wood',1).revenue;close(one.revenue,value);close(Commerce.quote(a,'wood'),Commerce.quote(b,'wood'));});
test('экспорт ограничен общим кошельком покупателей; насыщение сохраняется на завтра',()=>{const s=new Simulation();s.commerce.outside.budget=3;const initial=Commerce.quote(s,'grain');for(const g of Object.keys(s.goods))Commerce.sellOutside(s,g,100000);assert.ok(s.commerce.outside.spent<=3+1e-8);const prior=s.commerce.outside.totalPaid;s.day++;Commerce.openMarket(s);assert.equal(s.commerce.outside.spent,0);assert.equal(s.commerce.outside.totalPaid,prior);assert.ok(Commerce.quote(s,'grain')<=initial);});
test('внутренний рост себестоимости не заставляет внешних покупателей платить больше',()=>{const s=new Simulation(),quote=Commerce.quote(s,'tools');s.commerce.prices.tools*=100;assert.equal(Commerce.quote(s,'tools'),quote);});
test('квота ноль и запрет импорта сохраняют запасы и деньги',()=>{const s=new Simulation();assert.ok(s.setOutsidePolicy({quota:0,privateExport:false,importEnabled:false}).ok);s.commerce.stock.tools=100;s.day=3;const dock=s.building('dock'),cash=dock.cash,stock=dock.stock.iron;s.tradeWithOutside();assert.equal(dock.cash,cash);assert.equal(dock.stock.iron,stock);assert.equal(Commerce.exportGoods(s),0);assert.equal(s.act('food').ok,false);assert.equal(s.setOutsidePolicy({quota:-1}).ok,false);assert.deepEqual(copy(s).toJSON(),s.toJSON());});
test('содержание растёт с городом, учитывается в расходах и не взимается дважды',()=>{const s=new Simulation();s.treasury=1000;s.day=1;const before=s.treasury,cost=Object.values(Finance.upkeep(s)).reduce((a,b)=>a+b,0);Finance.maintain(s);close(s.treasury,before-cost+s.fiscal.infrastructure.procurement.localSpent*Finance.rate(s,'sales')/100);close(s.reportArchive.expenses.infrastructure,cost);Finance.maintain(s);close(s.treasury,before-cost+s.fiscal.infrastructure.procurement.localSpent*Finance.rate(s,'sales')/100);s.startConstruction('new1','home');s.day+=3;require('../expansion.js').tick(s);assert.ok(Object.values(Finance.upkeep(s)).reduce((a,b)=>a+b,0)>cost);});
test('бедная казна не уходит в минус: долг по содержанию и состояние дорог сохраняются',()=>{const s=new Simulation();s.day=1;s.treasury=20;Finance.maintain(s);assert.equal(s.treasury,20);assert.ok(s.fiscal.infrastructure.arrears>0);assert.ok(s.fiscal.infrastructure.condition<100);assert.deepEqual(copy(s).toJSON(),s.toJSON());});
test('старый город получает внешние лимиты без ретроспективного списания',()=>{const s=new Simulation(),data=s.toJSON();delete data.state.commerce.outside;delete data.state.fiscal.infrastructure;const r=Simulation.fromJSON(JSON.parse(JSON.stringify(data)));assert.equal(r.treasury,s.treasury);assert.equal(r.commerce.outside.totalPaid,0);assert.equal(r.fiscal.infrastructure.paid,0);});
test('повреждённый внешний рынок отклоняется при загрузке',()=>{const s=new Simulation();s.commerce.outside.pressure.tools=-100;assert.throws(()=>copy(s),/внешний рынок/);});

test('мастерская может отказаться от убыточной цены без потери товара и спроса',()=>{const s=new Simulation(),b=s.building('bakery'),floor=Commerce.exportFloor(s,b),o=s.commerce.outside;o.pressure.bread=10000;const sold=o.sold.bread||0,deal=Commerce.sellOutside(s,'bread',30,floor);assert.equal(deal.amount,0);assert.equal(deal.revenue,0);assert.equal(o.sold.bread||0,sold);});
test('богатая коммерческая лавка возмещает свою долю городского продовольствия',()=>{const s=new Simulation();s.day=1;s.treasury=1000;for(const b of s.buildings)b.stock.bread=b.stock.fish=0;s.building('market').cash=500;s.newDay();assert.equal(s.reportArchive.income.marketRepayment,48);assert.ok(s.building('market').cash<=452);assert.ok(s.building('market').stock.bread>=80);});

test('производство приостанавливается при переполнении и возобновляется после продаж',()=>{const {TYPES}=require('../sim.js'),s=new Simulation(),b=s.building('wood');Commerce.productionLimits(s,TYPES);b.stock.wood=b.enterprise.stockLimit+1;assert.equal(s.canProduce(b),false);b.stock.wood=0;assert.equal(s.canProduce(b),true);});
test('массовые поставки насыщают рынок на несколько дней, обычное потребление его разгружает',()=>{const s=new Simulation(),price=Commerce.quote(s,'tools');Commerce.sellOutside(s,'tools',1000);s.day++;Commerce.openMarket(s);assert.ok(Commerce.quote(s,'tools')<price);s.day+=2;Commerce.openMarket(s);close(Commerce.quote(s,'tools'),price);});

test('нулевые кошельки детей не заставляют бургомистра отменять налог взрослым',()=>{const s=new Simulation();for(const p of s.alive){p.coins=p.age<16?0:40;p.hunger=100;}s.treasury=0;s.day=1;Finance.daily(s);assert.equal(s.fiscal.taxes.income.rate,14);});
